// Code generated by protoc-gen-go. DO NOT EDIT.
// source: m3point.proto

package m3api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PointMsg struct {
	X                    int32    `protobuf:"zigzag32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"zigzag32,3,opt,name=y,proto3" json:"y,omitempty"`
	Z                    int32    `protobuf:"zigzag32,4,opt,name=z,proto3" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PointMsg) Reset()         { *m = PointMsg{} }
func (m *PointMsg) String() string { return proto.CompactTextString(m) }
func (*PointMsg) ProtoMessage()    {}
func (*PointMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_168a29c33716c6bb, []int{0}
}

func (m *PointMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PointMsg.Unmarshal(m, b)
}
func (m *PointMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PointMsg.Marshal(b, m, deterministic)
}
func (m *PointMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PointMsg.Merge(m, src)
}
func (m *PointMsg) XXX_Size() int {
	return xxx_messageInfo_PointMsg.Size(m)
}
func (m *PointMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PointMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PointMsg proto.InternalMessageInfo

func (m *PointMsg) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *PointMsg) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *PointMsg) GetZ() int32 {
	if m != nil {
		return m.Z
	}
	return 0
}

type ConnectionMsg struct {
	ConnId               int32     `protobuf:"zigzag32,1,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	Vector               *PointMsg `protobuf:"bytes,2,opt,name=vector,proto3" json:"vector,omitempty"`
	Ds                   int64     `protobuf:"varint,3,opt,name=ds,proto3" json:"ds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ConnectionMsg) Reset()         { *m = ConnectionMsg{} }
func (m *ConnectionMsg) String() string { return proto.CompactTextString(m) }
func (*ConnectionMsg) ProtoMessage()    {}
func (*ConnectionMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_168a29c33716c6bb, []int{1}
}

func (m *ConnectionMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionMsg.Unmarshal(m, b)
}
func (m *ConnectionMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionMsg.Marshal(b, m, deterministic)
}
func (m *ConnectionMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionMsg.Merge(m, src)
}
func (m *ConnectionMsg) XXX_Size() int {
	return xxx_messageInfo_ConnectionMsg.Size(m)
}
func (m *ConnectionMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionMsg proto.InternalMessageInfo

func (m *ConnectionMsg) GetConnId() int32 {
	if m != nil {
		return m.ConnId
	}
	return 0
}

func (m *ConnectionMsg) GetVector() *PointMsg {
	if m != nil {
		return m.Vector
	}
	return nil
}

func (m *ConnectionMsg) GetDs() int64 {
	if m != nil {
		return m.Ds
	}
	return 0
}

type TrioMsg struct {
	TrioId               int32    `protobuf:"varint,1,opt,name=trio_id,json=trioId,proto3" json:"trio_id,omitempty"`
	ConnIds              []int32  `protobuf:"zigzag32,2,rep,packed,name=conn_ids,json=connIds,proto3" json:"conn_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrioMsg) Reset()         { *m = TrioMsg{} }
func (m *TrioMsg) String() string { return proto.CompactTextString(m) }
func (*TrioMsg) ProtoMessage()    {}
func (*TrioMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_168a29c33716c6bb, []int{2}
}

func (m *TrioMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrioMsg.Unmarshal(m, b)
}
func (m *TrioMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrioMsg.Marshal(b, m, deterministic)
}
func (m *TrioMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrioMsg.Merge(m, src)
}
func (m *TrioMsg) XXX_Size() int {
	return xxx_messageInfo_TrioMsg.Size(m)
}
func (m *TrioMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_TrioMsg.DiscardUnknown(m)
}

var xxx_messageInfo_TrioMsg proto.InternalMessageInfo

func (m *TrioMsg) GetTrioId() int32 {
	if m != nil {
		return m.TrioId
	}
	return 0
}

func (m *TrioMsg) GetConnIds() []int32 {
	if m != nil {
		return m.ConnIds
	}
	return nil
}

type GrowthContextMsg struct {
	GrowthContextId      int32    `protobuf:"varint,1,opt,name=growth_context_id,json=growthContextId,proto3" json:"growth_context_id,omitempty"`
	GrowthType           int32    `protobuf:"varint,2,opt,name=growth_type,json=growthType,proto3" json:"growth_type,omitempty"`
	GrowthIndex          int32    `protobuf:"varint,3,opt,name=growth_index,json=growthIndex,proto3" json:"growth_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrowthContextMsg) Reset()         { *m = GrowthContextMsg{} }
func (m *GrowthContextMsg) String() string { return proto.CompactTextString(m) }
func (*GrowthContextMsg) ProtoMessage()    {}
func (*GrowthContextMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_168a29c33716c6bb, []int{3}
}

func (m *GrowthContextMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrowthContextMsg.Unmarshal(m, b)
}
func (m *GrowthContextMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrowthContextMsg.Marshal(b, m, deterministic)
}
func (m *GrowthContextMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrowthContextMsg.Merge(m, src)
}
func (m *GrowthContextMsg) XXX_Size() int {
	return xxx_messageInfo_GrowthContextMsg.Size(m)
}
func (m *GrowthContextMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_GrowthContextMsg.DiscardUnknown(m)
}

var xxx_messageInfo_GrowthContextMsg proto.InternalMessageInfo

func (m *GrowthContextMsg) GetGrowthContextId() int32 {
	if m != nil {
		return m.GrowthContextId
	}
	return 0
}

func (m *GrowthContextMsg) GetGrowthType() int32 {
	if m != nil {
		return m.GrowthType
	}
	return 0
}

func (m *GrowthContextMsg) GetGrowthIndex() int32 {
	if m != nil {
		return m.GrowthIndex
	}
	return 0
}

type CubeOfTrioMsg struct {
	CubeId               int32    `protobuf:"varint,1,opt,name=cube_id,json=cubeId,proto3" json:"cube_id,omitempty"`
	GrowthContextId      int32    `protobuf:"varint,2,opt,name=growth_context_id,json=growthContextId,proto3" json:"growth_context_id,omitempty"`
	CenterTrioId         int32    `protobuf:"varint,3,opt,name=center_trio_id,json=centerTrioId,proto3" json:"center_trio_id,omitempty"`
	CenterFacesTrioIds   []int32  `protobuf:"varint,4,rep,packed,name=center_faces_trio_ids,json=centerFacesTrioIds,proto3" json:"center_faces_trio_ids,omitempty"`
	MiddleEdgesTrioIds   []int32  `protobuf:"varint,5,rep,packed,name=middle_edges_trio_ids,json=middleEdgesTrioIds,proto3" json:"middle_edges_trio_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CubeOfTrioMsg) Reset()         { *m = CubeOfTrioMsg{} }
func (m *CubeOfTrioMsg) String() string { return proto.CompactTextString(m) }
func (*CubeOfTrioMsg) ProtoMessage()    {}
func (*CubeOfTrioMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_168a29c33716c6bb, []int{4}
}

func (m *CubeOfTrioMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CubeOfTrioMsg.Unmarshal(m, b)
}
func (m *CubeOfTrioMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CubeOfTrioMsg.Marshal(b, m, deterministic)
}
func (m *CubeOfTrioMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CubeOfTrioMsg.Merge(m, src)
}
func (m *CubeOfTrioMsg) XXX_Size() int {
	return xxx_messageInfo_CubeOfTrioMsg.Size(m)
}
func (m *CubeOfTrioMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_CubeOfTrioMsg.DiscardUnknown(m)
}

var xxx_messageInfo_CubeOfTrioMsg proto.InternalMessageInfo

func (m *CubeOfTrioMsg) GetCubeId() int32 {
	if m != nil {
		return m.CubeId
	}
	return 0
}

func (m *CubeOfTrioMsg) GetGrowthContextId() int32 {
	if m != nil {
		return m.GrowthContextId
	}
	return 0
}

func (m *CubeOfTrioMsg) GetCenterTrioId() int32 {
	if m != nil {
		return m.CenterTrioId
	}
	return 0
}

func (m *CubeOfTrioMsg) GetCenterFacesTrioIds() []int32 {
	if m != nil {
		return m.CenterFacesTrioIds
	}
	return nil
}

func (m *CubeOfTrioMsg) GetMiddleEdgesTrioIds() []int32 {
	if m != nil {
		return m.MiddleEdgesTrioIds
	}
	return nil
}

type RootPathNodeBuilderMsg struct {
	CubeId               int32                             `protobuf:"varint,1,opt,name=cube_id,json=cubeId,proto3" json:"cube_id,omitempty"`
	TrioId               int32                             `protobuf:"varint,2,opt,name=trio_id,json=trioId,proto3" json:"trio_id,omitempty"`
	InterNodeBuilders    []*IntermediatePathNodeBuilderMsg `protobuf:"bytes,3,rep,name=inter_node_builders,json=interNodeBuilders,proto3" json:"inter_node_builders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *RootPathNodeBuilderMsg) Reset()         { *m = RootPathNodeBuilderMsg{} }
func (m *RootPathNodeBuilderMsg) String() string { return proto.CompactTextString(m) }
func (*RootPathNodeBuilderMsg) ProtoMessage()    {}
func (*RootPathNodeBuilderMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_168a29c33716c6bb, []int{5}
}

func (m *RootPathNodeBuilderMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RootPathNodeBuilderMsg.Unmarshal(m, b)
}
func (m *RootPathNodeBuilderMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RootPathNodeBuilderMsg.Marshal(b, m, deterministic)
}
func (m *RootPathNodeBuilderMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RootPathNodeBuilderMsg.Merge(m, src)
}
func (m *RootPathNodeBuilderMsg) XXX_Size() int {
	return xxx_messageInfo_RootPathNodeBuilderMsg.Size(m)
}
func (m *RootPathNodeBuilderMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_RootPathNodeBuilderMsg.DiscardUnknown(m)
}

var xxx_messageInfo_RootPathNodeBuilderMsg proto.InternalMessageInfo

func (m *RootPathNodeBuilderMsg) GetCubeId() int32 {
	if m != nil {
		return m.CubeId
	}
	return 0
}

func (m *RootPathNodeBuilderMsg) GetTrioId() int32 {
	if m != nil {
		return m.TrioId
	}
	return 0
}

func (m *RootPathNodeBuilderMsg) GetInterNodeBuilders() []*IntermediatePathNodeBuilderMsg {
	if m != nil {
		return m.InterNodeBuilders
	}
	return nil
}

type IntermediatePathNodeBuilderMsg struct {
	CubeId               int32                   `protobuf:"varint,1,opt,name=cube_id,json=cubeId,proto3" json:"cube_id,omitempty"`
	TrioId               int32                   `protobuf:"varint,2,opt,name=trio_id,json=trioId,proto3" json:"trio_id,omitempty"`
	Link1ConnId          int32                   `protobuf:"zigzag32,3,opt,name=link1_conn_id,json=link1ConnId,proto3" json:"link1_conn_id,omitempty"`
	LastNodeBuilder1     *LastPathNodeBuilderMsg `protobuf:"bytes,4,opt,name=last_node_builder1,json=lastNodeBuilder1,proto3" json:"last_node_builder1,omitempty"`
	Link2ConnId          int32                   `protobuf:"zigzag32,5,opt,name=link2_conn_id,json=link2ConnId,proto3" json:"link2_conn_id,omitempty"`
	LastNodeBuilder2     *LastPathNodeBuilderMsg `protobuf:"bytes,6,opt,name=last_node_builder2,json=lastNodeBuilder2,proto3" json:"last_node_builder2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *IntermediatePathNodeBuilderMsg) Reset()         { *m = IntermediatePathNodeBuilderMsg{} }
func (m *IntermediatePathNodeBuilderMsg) String() string { return proto.CompactTextString(m) }
func (*IntermediatePathNodeBuilderMsg) ProtoMessage()    {}
func (*IntermediatePathNodeBuilderMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_168a29c33716c6bb, []int{6}
}

func (m *IntermediatePathNodeBuilderMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntermediatePathNodeBuilderMsg.Unmarshal(m, b)
}
func (m *IntermediatePathNodeBuilderMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntermediatePathNodeBuilderMsg.Marshal(b, m, deterministic)
}
func (m *IntermediatePathNodeBuilderMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntermediatePathNodeBuilderMsg.Merge(m, src)
}
func (m *IntermediatePathNodeBuilderMsg) XXX_Size() int {
	return xxx_messageInfo_IntermediatePathNodeBuilderMsg.Size(m)
}
func (m *IntermediatePathNodeBuilderMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_IntermediatePathNodeBuilderMsg.DiscardUnknown(m)
}

var xxx_messageInfo_IntermediatePathNodeBuilderMsg proto.InternalMessageInfo

func (m *IntermediatePathNodeBuilderMsg) GetCubeId() int32 {
	if m != nil {
		return m.CubeId
	}
	return 0
}

func (m *IntermediatePathNodeBuilderMsg) GetTrioId() int32 {
	if m != nil {
		return m.TrioId
	}
	return 0
}

func (m *IntermediatePathNodeBuilderMsg) GetLink1ConnId() int32 {
	if m != nil {
		return m.Link1ConnId
	}
	return 0
}

func (m *IntermediatePathNodeBuilderMsg) GetLastNodeBuilder1() *LastPathNodeBuilderMsg {
	if m != nil {
		return m.LastNodeBuilder1
	}
	return nil
}

func (m *IntermediatePathNodeBuilderMsg) GetLink2ConnId() int32 {
	if m != nil {
		return m.Link2ConnId
	}
	return 0
}

func (m *IntermediatePathNodeBuilderMsg) GetLastNodeBuilder2() *LastPathNodeBuilderMsg {
	if m != nil {
		return m.LastNodeBuilder2
	}
	return nil
}

type LastPathNodeBuilderMsg struct {
	CubeId               int32    `protobuf:"varint,1,opt,name=cube_id,json=cubeId,proto3" json:"cube_id,omitempty"`
	TrioId               int32    `protobuf:"varint,2,opt,name=trio_id,json=trioId,proto3" json:"trio_id,omitempty"`
	NextMainConnId       int32    `protobuf:"zigzag32,3,opt,name=next_main_conn_id,json=nextMainConnId,proto3" json:"next_main_conn_id,omitempty"`
	NextInterConnId      int32    `protobuf:"zigzag32,4,opt,name=next_inter_conn_id,json=nextInterConnId,proto3" json:"next_inter_conn_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LastPathNodeBuilderMsg) Reset()         { *m = LastPathNodeBuilderMsg{} }
func (m *LastPathNodeBuilderMsg) String() string { return proto.CompactTextString(m) }
func (*LastPathNodeBuilderMsg) ProtoMessage()    {}
func (*LastPathNodeBuilderMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_168a29c33716c6bb, []int{7}
}

func (m *LastPathNodeBuilderMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LastPathNodeBuilderMsg.Unmarshal(m, b)
}
func (m *LastPathNodeBuilderMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LastPathNodeBuilderMsg.Marshal(b, m, deterministic)
}
func (m *LastPathNodeBuilderMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastPathNodeBuilderMsg.Merge(m, src)
}
func (m *LastPathNodeBuilderMsg) XXX_Size() int {
	return xxx_messageInfo_LastPathNodeBuilderMsg.Size(m)
}
func (m *LastPathNodeBuilderMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_LastPathNodeBuilderMsg.DiscardUnknown(m)
}

var xxx_messageInfo_LastPathNodeBuilderMsg proto.InternalMessageInfo

func (m *LastPathNodeBuilderMsg) GetCubeId() int32 {
	if m != nil {
		return m.CubeId
	}
	return 0
}

func (m *LastPathNodeBuilderMsg) GetTrioId() int32 {
	if m != nil {
		return m.TrioId
	}
	return 0
}

func (m *LastPathNodeBuilderMsg) GetNextMainConnId() int32 {
	if m != nil {
		return m.NextMainConnId
	}
	return 0
}

func (m *LastPathNodeBuilderMsg) GetNextInterConnId() int32 {
	if m != nil {
		return m.NextInterConnId
	}
	return 0
}

type PointPackDataMsg struct {
	AllConnections       []*ConnectionMsg          `protobuf:"bytes,1,rep,name=all_connections,json=allConnections,proto3" json:"all_connections,omitempty"`
	AllTrios             []*TrioMsg                `protobuf:"bytes,2,rep,name=all_trios,json=allTrios,proto3" json:"all_trios,omitempty"`
	AllGrowthContexts    []*GrowthContextMsg       `protobuf:"bytes,3,rep,name=all_growth_contexts,json=allGrowthContexts,proto3" json:"all_growth_contexts,omitempty"`
	AllCubes             []*CubeOfTrioMsg          `protobuf:"bytes,4,rep,name=all_cubes,json=allCubes,proto3" json:"all_cubes,omitempty"`
	AllPathNodeBuilders  []*RootPathNodeBuilderMsg `protobuf:"bytes,5,rep,name=all_path_node_builders,json=allPathNodeBuilders,proto3" json:"all_path_node_builders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *PointPackDataMsg) Reset()         { *m = PointPackDataMsg{} }
func (m *PointPackDataMsg) String() string { return proto.CompactTextString(m) }
func (*PointPackDataMsg) ProtoMessage()    {}
func (*PointPackDataMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_168a29c33716c6bb, []int{8}
}

func (m *PointPackDataMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PointPackDataMsg.Unmarshal(m, b)
}
func (m *PointPackDataMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PointPackDataMsg.Marshal(b, m, deterministic)
}
func (m *PointPackDataMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PointPackDataMsg.Merge(m, src)
}
func (m *PointPackDataMsg) XXX_Size() int {
	return xxx_messageInfo_PointPackDataMsg.Size(m)
}
func (m *PointPackDataMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PointPackDataMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PointPackDataMsg proto.InternalMessageInfo

func (m *PointPackDataMsg) GetAllConnections() []*ConnectionMsg {
	if m != nil {
		return m.AllConnections
	}
	return nil
}

func (m *PointPackDataMsg) GetAllTrios() []*TrioMsg {
	if m != nil {
		return m.AllTrios
	}
	return nil
}

func (m *PointPackDataMsg) GetAllGrowthContexts() []*GrowthContextMsg {
	if m != nil {
		return m.AllGrowthContexts
	}
	return nil
}

func (m *PointPackDataMsg) GetAllCubes() []*CubeOfTrioMsg {
	if m != nil {
		return m.AllCubes
	}
	return nil
}

func (m *PointPackDataMsg) GetAllPathNodeBuilders() []*RootPathNodeBuilderMsg {
	if m != nil {
		return m.AllPathNodeBuilders
	}
	return nil
}

func init() {
	proto.RegisterType((*PointMsg)(nil), "m3api.PointMsg")
	proto.RegisterType((*ConnectionMsg)(nil), "m3api.ConnectionMsg")
	proto.RegisterType((*TrioMsg)(nil), "m3api.TrioMsg")
	proto.RegisterType((*GrowthContextMsg)(nil), "m3api.GrowthContextMsg")
	proto.RegisterType((*CubeOfTrioMsg)(nil), "m3api.CubeOfTrioMsg")
	proto.RegisterType((*RootPathNodeBuilderMsg)(nil), "m3api.RootPathNodeBuilderMsg")
	proto.RegisterType((*IntermediatePathNodeBuilderMsg)(nil), "m3api.IntermediatePathNodeBuilderMsg")
	proto.RegisterType((*LastPathNodeBuilderMsg)(nil), "m3api.LastPathNodeBuilderMsg")
	proto.RegisterType((*PointPackDataMsg)(nil), "m3api.PointPackDataMsg")
}

func init() {
	proto.RegisterFile("m3point.proto", fileDescriptor_168a29c33716c6bb)
}

var fileDescriptor_168a29c33716c6bb = []byte{
	// 670 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0x9d, 0x3a, 0x2d, 0x93, 0x26, 0x69, 0x5c, 0x68, 0xcd, 0x01, 0x28, 0x16, 0x88, 0x40,
	0xa5, 0x4a, 0x71, 0xb9, 0xf6, 0x42, 0x80, 0x2a, 0x82, 0x42, 0xb5, 0x2a, 0xe7, 0x68, 0xe3, 0xdd,
	0xa6, 0x56, 0x9d, 0xdd, 0xc8, 0xbb, 0x85, 0xa4, 0x47, 0xfe, 0x04, 0xbe, 0x81, 0xef, 0xe0, 0x1b,
	0xf8, 0x14, 0x34, 0xbb, 0x6b, 0xea, 0x84, 0xa8, 0x87, 0xde, 0x32, 0x6f, 0xe6, 0xed, 0x9b, 0x19,
	0xcf, 0x4c, 0xa0, 0x39, 0x39, 0x9c, 0xca, 0x4c, 0xe8, 0x83, 0x69, 0x21, 0xb5, 0x0c, 0x83, 0xc9,
	0x21, 0x9d, 0x66, 0xf1, 0x6b, 0xd8, 0x38, 0x45, 0xf4, 0x44, 0x8d, 0xc3, 0x4d, 0xf0, 0x66, 0x91,
	0xbf, 0xe7, 0x75, 0x3b, 0xc4, 0x9b, 0xa1, 0x35, 0x8f, 0x6a, 0xd6, 0x9a, 0xa3, 0x75, 0x1d, 0xad,
	0x59, 0xeb, 0x3a, 0xa6, 0xd0, 0xec, 0x4b, 0x21, 0x78, 0xaa, 0x33, 0x29, 0x90, 0xba, 0x0b, 0xeb,
	0xa9, 0x14, 0x62, 0x98, 0xb1, 0xc8, 0x33, 0x41, 0x75, 0x34, 0x07, 0x2c, 0x7c, 0x01, 0xf5, 0xaf,
	0x3c, 0xd5, 0xb2, 0x30, 0x0f, 0x37, 0x92, 0xf6, 0x81, 0xd1, 0x3d, 0x28, 0x45, 0x89, 0x73, 0x87,
	0x2d, 0xf0, 0x99, 0x32, 0x7a, 0x35, 0xe2, 0x33, 0x15, 0x1f, 0xc1, 0xfa, 0x59, 0x91, 0x49, 0xf7,
	0xb8, 0x2e, 0x32, 0x59, 0x3e, 0x1e, 0x90, 0x3a, 0x9a, 0x03, 0x16, 0x3e, 0x84, 0x0d, 0xa7, 0xaa,
	0x22, 0x7f, 0xaf, 0xd6, 0xed, 0x90, 0x75, 0x2b, 0xab, 0xe2, 0xef, 0x1e, 0x6c, 0x1d, 0x17, 0xf2,
	0x9b, 0xbe, 0xe8, 0x4b, 0xa1, 0xf9, 0xcc, 0x14, 0xf8, 0x0a, 0x3a, 0x63, 0x83, 0x0d, 0x53, 0x0b,
	0xde, 0x3c, 0xd9, 0x1e, 0x57, 0x83, 0x07, 0x2c, 0x7c, 0x02, 0x0d, 0x17, 0xab, 0xe7, 0x53, 0x6e,
	0xb2, 0x0f, 0x08, 0x58, 0xe8, 0x6c, 0x3e, 0xe5, 0xe1, 0x53, 0xd8, 0x74, 0x01, 0x99, 0x60, 0x7c,
	0x66, 0x52, 0x0f, 0x88, 0x23, 0x0d, 0x10, 0x8a, 0xff, 0x78, 0xd0, 0xec, 0x5f, 0x8d, 0xf8, 0xe7,
	0xf3, 0x4a, 0x29, 0xe9, 0xd5, 0x88, 0x57, 0x4a, 0x41, 0x73, 0xc0, 0x56, 0xa7, 0xe6, 0xaf, 0x4e,
	0xed, 0x19, 0xb4, 0x52, 0x2e, 0x34, 0x2f, 0x86, 0x65, 0x5b, 0xac, 0xf6, 0xa6, 0x45, 0xcf, 0x6c,
	0x73, 0x7a, 0xf0, 0xc0, 0x45, 0x9d, 0xd3, 0x94, 0xab, 0x32, 0x56, 0x45, 0x6b, 0x7b, 0xb5, 0x6e,
	0x40, 0x42, 0xeb, 0x7c, 0x8f, 0x3e, 0xcb, 0x50, 0x48, 0x99, 0x64, 0x8c, 0xe5, 0x7c, 0xc8, 0xd9,
	0xb8, 0x4a, 0x09, 0x2c, 0xc5, 0x3a, 0xdf, 0xa1, 0xcf, 0x51, 0xe2, 0x1f, 0x1e, 0xec, 0x10, 0x29,
	0xf5, 0x29, 0xd5, 0x17, 0x9f, 0x24, 0xe3, 0x6f, 0xae, 0xb2, 0x9c, 0xf1, 0xe2, 0xd6, 0x5a, 0x2b,
	0xdf, 0xd3, 0x5f, 0xf8, 0x9e, 0x5f, 0x60, 0x3b, 0x33, 0x19, 0x0b, 0xc9, 0xf8, 0x70, 0x64, 0x9f,
	0xc2, 0xa1, 0xa8, 0x75, 0x1b, 0xc9, 0x73, 0x37, 0x39, 0x03, 0x8c, 0x98, 0x70, 0x96, 0x51, 0xcd,
	0xff, 0x57, 0x25, 0x1d, 0xf3, 0x42, 0x05, 0x54, 0xf1, 0x2f, 0x1f, 0x1e, 0xdf, 0xce, 0xba, 0x43,
	0xae, 0x31, 0x34, 0xf3, 0x4c, 0x5c, 0xf6, 0x86, 0xe5, 0xdc, 0xdb, 0x55, 0x69, 0x18, 0xb0, 0x6f,
	0x87, 0xff, 0x03, 0x84, 0x39, 0x55, 0x7a, 0xa1, 0x9c, 0x9e, 0xd9, 0xa2, 0x46, 0xf2, 0xc8, 0x95,
	0xf3, 0x91, 0xaa, 0x15, 0xcd, 0x23, 0x5b, 0x48, 0xac, 0x60, 0xbd, 0x52, 0x30, 0xf9, 0x27, 0x18,
	0xdc, 0x08, 0x26, 0xb7, 0x08, 0x26, 0x51, 0xfd, 0x2e, 0x82, 0x49, 0xfc, 0xd3, 0x83, 0x9d, 0xd5,
	0xc1, 0x77, 0x68, 0xd7, 0x4b, 0xe8, 0x08, 0x9c, 0xea, 0x09, 0xcd, 0xc4, 0x52, 0xcb, 0x5a, 0xe8,
	0x38, 0xa1, 0x99, 0x70, 0x45, 0xec, 0x43, 0x68, 0x42, 0xed, 0x28, 0x94, 0xb1, 0xf6, 0xf6, 0xb4,
	0xd1, 0x63, 0xbe, 0xa5, 0x0d, 0x8e, 0x7f, 0xfb, 0xb0, 0x65, 0x6e, 0xc9, 0x29, 0x4d, 0x2f, 0xdf,
	0x52, 0x4d, 0x31, 0xbd, 0x23, 0x68, 0xd3, 0x3c, 0x37, 0x54, 0x7b, 0xa2, 0x54, 0xe4, 0x99, 0x19,
	0xba, 0xef, 0x7a, 0xb0, 0x70, 0xbc, 0x48, 0x8b, 0xe6, 0xf9, 0x0d, 0xa2, 0xc2, 0x7d, 0xb8, 0x87,
	0x74, 0xcc, 0xdc, 0xde, 0x95, 0x46, 0xd2, 0x72, 0x44, 0xb7, 0xc7, 0x64, 0x83, 0xe6, 0x39, 0xfe,
	0x56, 0xe1, 0x31, 0x6c, 0x63, 0xf0, 0xe2, 0xf2, 0x96, 0x33, 0xbb, 0xeb, 0x68, 0xcb, 0x97, 0x88,
	0x74, 0x68, 0x9e, 0x2f, 0x80, 0xb8, 0x7c, 0x46, 0x15, 0x1b, 0x69, 0x77, 0xb4, 0x92, 0x6e, 0xf5,
	0x86, 0x18, 0x6d, 0x44, 0x54, 0x48, 0x60, 0x07, 0x29, 0x53, 0xaa, 0x2f, 0x96, 0x56, 0x26, 0x30,
	0xfc, 0xf2, 0x93, 0xaf, 0x5e, 0x50, 0x82, 0x89, 0x2f, 0xc1, 0x6a, 0x54, 0x37, 0x7f, 0x0f, 0x87,
	0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x2d, 0xf4, 0xe4, 0xe2, 0x2f, 0x06, 0x00, 0x00,
}
