version: '3.1'
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: web.Dockerfile
      args:
        REACT_APP_BACKEND_URL: "http://backend:8063"
    ports:
      - 8082:8080

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend.Dockerfile
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: qsm
      DB_PASSWORD: qsm
      DB_NAME: qsm
      SERVER_PORT: 8063
    ports:
      - 8063:8063
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: fredsimon-docker.jfrog.io/postgres:12.3
    restart: always
    tmpfs:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_DB: qsm
      POSTGRES_USER: qsm
      POSTGRES_PASSWORD: qsm
    ports:
      - 5432:5432/tcp
    command: -c fsync=off -c max_connections=200 -c full_page_writes=off

  adminer:
    container_name: adminer
    image: fredsimon-docker.jfrog.io/adminer:4.7
    restart: always
    ports:
      - 8081:8080
