version: '3.1'
services:
  job-filldb:
    build:
      context: .
      dockerfile: job-filldb.Dockerfile
    container_name: qsm
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: qsm
      DB_PASSWORD: qsm
      DB_NAME: qsm
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:12.3
    restart: always
    environment:
      POSTGRES_DB: qsm
      POSTGRES_USER: qsm
      POSTGRES_PASSWORD: qsm
    ports:
      - 5432:5432

  adminer:
    container_name: adminer
    image: adminer:4.7
    restart: always
    ports:
      - 8081:8080