#!/usr/bin/env bash

QSM_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd )"
if [ -e "$QSM_HOME/.git" ]; then
    echo "INFO: Using root repo dir $QSM_HOME"
else
    echo "ERROR: Did not find root git repo dir at $QSM_HOME"
    exit 2
fi
export QSM_HOME

if [ -z "$1" ]; then
    echo "INFO: Usage $0 [-env number] (db run test bench)"
    exit 0
fi

if [ "$1" == "-env" ]; then
    if [ -z "$2" ]; then
        echo "ERROR: after -env need a number"
        exit 4
    fi
    export QSM_ENV_NUMBER=$2
    shift
    shift
fi

script=$1
shift

cd $QSM_HOME && ./scripts/${script}.sh $@
