// source: m3point.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.m3api.ConnectionMsg', null, global);
goog.exportSymbol('proto.m3api.CubeOfTrioMsg', null, global);
goog.exportSymbol('proto.m3api.GrowthContextMsg', null, global);
goog.exportSymbol('proto.m3api.IntermediatePathNodeBuilderMsg', null, global);
goog.exportSymbol('proto.m3api.LastPathNodeBuilderMsg', null, global);
goog.exportSymbol('proto.m3api.PointMsg', null, global);
goog.exportSymbol('proto.m3api.PointPackDataMsg', null, global);
goog.exportSymbol('proto.m3api.RootPathNodeBuilderMsg', null, global);
goog.exportSymbol('proto.m3api.TrioMsg', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.m3api.PointMsg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.m3api.PointMsg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.m3api.PointMsg.displayName = 'proto.m3api.PointMsg';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.m3api.ConnectionMsg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.m3api.ConnectionMsg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.m3api.ConnectionMsg.displayName = 'proto.m3api.ConnectionMsg';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.m3api.TrioMsg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.m3api.TrioMsg.repeatedFields_, null);
};
goog.inherits(proto.m3api.TrioMsg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.m3api.TrioMsg.displayName = 'proto.m3api.TrioMsg';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.m3api.GrowthContextMsg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.m3api.GrowthContextMsg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.m3api.GrowthContextMsg.displayName = 'proto.m3api.GrowthContextMsg';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.m3api.CubeOfTrioMsg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.m3api.CubeOfTrioMsg.repeatedFields_, null);
};
goog.inherits(proto.m3api.CubeOfTrioMsg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.m3api.CubeOfTrioMsg.displayName = 'proto.m3api.CubeOfTrioMsg';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.m3api.RootPathNodeBuilderMsg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.m3api.RootPathNodeBuilderMsg.repeatedFields_, null);
};
goog.inherits(proto.m3api.RootPathNodeBuilderMsg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.m3api.RootPathNodeBuilderMsg.displayName = 'proto.m3api.RootPathNodeBuilderMsg';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.m3api.IntermediatePathNodeBuilderMsg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.m3api.IntermediatePathNodeBuilderMsg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.m3api.IntermediatePathNodeBuilderMsg.displayName = 'proto.m3api.IntermediatePathNodeBuilderMsg';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.m3api.LastPathNodeBuilderMsg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.m3api.LastPathNodeBuilderMsg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.m3api.LastPathNodeBuilderMsg.displayName = 'proto.m3api.LastPathNodeBuilderMsg';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.m3api.PointPackDataMsg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.m3api.PointPackDataMsg.repeatedFields_, null);
};
goog.inherits(proto.m3api.PointPackDataMsg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.m3api.PointPackDataMsg.displayName = 'proto.m3api.PointPackDataMsg';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.m3api.PointMsg.prototype.toObject = function(opt_includeInstance) {
  return proto.m3api.PointMsg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.m3api.PointMsg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.m3api.PointMsg.toObject = function(includeInstance, msg) {
  var f, obj = {
    x: jspb.Message.getFieldWithDefault(msg, 2, 0),
    y: jspb.Message.getFieldWithDefault(msg, 3, 0),
    z: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.m3api.PointMsg}
 */
proto.m3api.PointMsg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.m3api.PointMsg;
  return proto.m3api.PointMsg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.m3api.PointMsg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.m3api.PointMsg}
 */
proto.m3api.PointMsg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = /** @type {number} */ (reader.readSint32());
      msg.setX(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readSint32());
      msg.setY(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readSint32());
      msg.setZ(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.m3api.PointMsg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.m3api.PointMsg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.m3api.PointMsg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.m3api.PointMsg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getX();
  if (f !== 0) {
    writer.writeSint32(
      2,
      f
    );
  }
  f = message.getY();
  if (f !== 0) {
    writer.writeSint32(
      3,
      f
    );
  }
  f = message.getZ();
  if (f !== 0) {
    writer.writeSint32(
      4,
      f
    );
  }
};


/**
 * optional sint32 x = 2;
 * @return {number}
 */
proto.m3api.PointMsg.prototype.getX = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.m3api.PointMsg} returns this
 */
proto.m3api.PointMsg.prototype.setX = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional sint32 y = 3;
 * @return {number}
 */
proto.m3api.PointMsg.prototype.getY = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.m3api.PointMsg} returns this
 */
proto.m3api.PointMsg.prototype.setY = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional sint32 z = 4;
 * @return {number}
 */
proto.m3api.PointMsg.prototype.getZ = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.m3api.PointMsg} returns this
 */
proto.m3api.PointMsg.prototype.setZ = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.m3api.ConnectionMsg.prototype.toObject = function(opt_includeInstance) {
  return proto.m3api.ConnectionMsg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.m3api.ConnectionMsg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.m3api.ConnectionMsg.toObject = function(includeInstance, msg) {
  var f, obj = {
    connId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    vector: (f = msg.getVector()) && proto.m3api.PointMsg.toObject(includeInstance, f),
    ds: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.m3api.ConnectionMsg}
 */
proto.m3api.ConnectionMsg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.m3api.ConnectionMsg;
  return proto.m3api.ConnectionMsg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.m3api.ConnectionMsg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.m3api.ConnectionMsg}
 */
proto.m3api.ConnectionMsg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readSint32());
      msg.setConnId(value);
      break;
    case 2:
      var value = new proto.m3api.PointMsg;
      reader.readMessage(value,proto.m3api.PointMsg.deserializeBinaryFromReader);
      msg.setVector(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.m3api.ConnectionMsg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.m3api.ConnectionMsg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.m3api.ConnectionMsg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.m3api.ConnectionMsg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getConnId();
  if (f !== 0) {
    writer.writeSint32(
      1,
      f
    );
  }
  f = message.getVector();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.m3api.PointMsg.serializeBinaryToWriter
    );
  }
  f = message.getDs();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
};


/**
 * optional sint32 conn_id = 1;
 * @return {number}
 */
proto.m3api.ConnectionMsg.prototype.getConnId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.m3api.ConnectionMsg} returns this
 */
proto.m3api.ConnectionMsg.prototype.setConnId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional PointMsg vector = 2;
 * @return {?proto.m3api.PointMsg}
 */
proto.m3api.ConnectionMsg.prototype.getVector = function() {
  return /** @type{?proto.m3api.PointMsg} */ (
    jspb.Message.getWrapperField(this, proto.m3api.PointMsg, 2));
};


/**
 * @param {?proto.m3api.PointMsg|undefined} value
 * @return {!proto.m3api.ConnectionMsg} returns this
*/
proto.m3api.ConnectionMsg.prototype.setVector = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.m3api.ConnectionMsg} returns this
 */
proto.m3api.ConnectionMsg.prototype.clearVector = function() {
  return this.setVector(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.m3api.ConnectionMsg.prototype.hasVector = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional int64 ds = 3;
 * @return {number}
 */
proto.m3api.ConnectionMsg.prototype.getDs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.m3api.ConnectionMsg} returns this
 */
proto.m3api.ConnectionMsg.prototype.setDs = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.m3api.TrioMsg.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.m3api.TrioMsg.prototype.toObject = function(opt_includeInstance) {
  return proto.m3api.TrioMsg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.m3api.TrioMsg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.m3api.TrioMsg.toObject = function(includeInstance, msg) {
  var f, obj = {
    trioId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    connIdsList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.m3api.TrioMsg}
 */
proto.m3api.TrioMsg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.m3api.TrioMsg;
  return proto.m3api.TrioMsg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.m3api.TrioMsg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.m3api.TrioMsg}
 */
proto.m3api.TrioMsg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTrioId(value);
      break;
    case 2:
      var value = /** @type {!Array<number>} */ (reader.readPackedSint32());
      msg.setConnIdsList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.m3api.TrioMsg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.m3api.TrioMsg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.m3api.TrioMsg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.m3api.TrioMsg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTrioId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getConnIdsList();
  if (f.length > 0) {
    writer.writePackedSint32(
      2,
      f
    );
  }
};


/**
 * optional int32 trio_id = 1;
 * @return {number}
 */
proto.m3api.TrioMsg.prototype.getTrioId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.m3api.TrioMsg} returns this
 */
proto.m3api.TrioMsg.prototype.setTrioId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * repeated sint32 conn_ids = 2;
 * @return {!Array<number>}
 */
proto.m3api.TrioMsg.prototype.getConnIdsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.m3api.TrioMsg} returns this
 */
proto.m3api.TrioMsg.prototype.setConnIdsList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.m3api.TrioMsg} returns this
 */
proto.m3api.TrioMsg.prototype.addConnIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.m3api.TrioMsg} returns this
 */
proto.m3api.TrioMsg.prototype.clearConnIdsList = function() {
  return this.setConnIdsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.m3api.GrowthContextMsg.prototype.toObject = function(opt_includeInstance) {
  return proto.m3api.GrowthContextMsg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.m3api.GrowthContextMsg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.m3api.GrowthContextMsg.toObject = function(includeInstance, msg) {
  var f, obj = {
    growthContextId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    growthType: jspb.Message.getFieldWithDefault(msg, 2, 0),
    growthIndex: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.m3api.GrowthContextMsg}
 */
proto.m3api.GrowthContextMsg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.m3api.GrowthContextMsg;
  return proto.m3api.GrowthContextMsg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.m3api.GrowthContextMsg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.m3api.GrowthContextMsg}
 */
proto.m3api.GrowthContextMsg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setGrowthContextId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setGrowthType(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setGrowthIndex(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.m3api.GrowthContextMsg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.m3api.GrowthContextMsg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.m3api.GrowthContextMsg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.m3api.GrowthContextMsg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGrowthContextId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getGrowthType();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getGrowthIndex();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * optional int32 growth_context_id = 1;
 * @return {number}
 */
proto.m3api.GrowthContextMsg.prototype.getGrowthContextId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.m3api.GrowthContextMsg} returns this
 */
proto.m3api.GrowthContextMsg.prototype.setGrowthContextId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 growth_type = 2;
 * @return {number}
 */
proto.m3api.GrowthContextMsg.prototype.getGrowthType = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.m3api.GrowthContextMsg} returns this
 */
proto.m3api.GrowthContextMsg.prototype.setGrowthType = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 growth_index = 3;
 * @return {number}
 */
proto.m3api.GrowthContextMsg.prototype.getGrowthIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.m3api.GrowthContextMsg} returns this
 */
proto.m3api.GrowthContextMsg.prototype.setGrowthIndex = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.m3api.CubeOfTrioMsg.repeatedFields_ = [4,5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.m3api.CubeOfTrioMsg.prototype.toObject = function(opt_includeInstance) {
  return proto.m3api.CubeOfTrioMsg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.m3api.CubeOfTrioMsg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.m3api.CubeOfTrioMsg.toObject = function(includeInstance, msg) {
  var f, obj = {
    cubeId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    growthContextId: jspb.Message.getFieldWithDefault(msg, 2, 0),
    centerTrioId: jspb.Message.getFieldWithDefault(msg, 3, 0),
    centerFacesTrioIdsList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f,
    middleEdgesTrioIdsList: (f = jspb.Message.getRepeatedField(msg, 5)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.m3api.CubeOfTrioMsg}
 */
proto.m3api.CubeOfTrioMsg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.m3api.CubeOfTrioMsg;
  return proto.m3api.CubeOfTrioMsg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.m3api.CubeOfTrioMsg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.m3api.CubeOfTrioMsg}
 */
proto.m3api.CubeOfTrioMsg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCubeId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setGrowthContextId(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCenterTrioId(value);
      break;
    case 4:
      var value = /** @type {!Array<number>} */ (reader.readPackedInt32());
      msg.setCenterFacesTrioIdsList(value);
      break;
    case 5:
      var value = /** @type {!Array<number>} */ (reader.readPackedInt32());
      msg.setMiddleEdgesTrioIdsList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.m3api.CubeOfTrioMsg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.m3api.CubeOfTrioMsg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.m3api.CubeOfTrioMsg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.m3api.CubeOfTrioMsg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCubeId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getGrowthContextId();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getCenterTrioId();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getCenterFacesTrioIdsList();
  if (f.length > 0) {
    writer.writePackedInt32(
      4,
      f
    );
  }
  f = message.getMiddleEdgesTrioIdsList();
  if (f.length > 0) {
    writer.writePackedInt32(
      5,
      f
    );
  }
};


/**
 * optional int32 cube_id = 1;
 * @return {number}
 */
proto.m3api.CubeOfTrioMsg.prototype.getCubeId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.m3api.CubeOfTrioMsg} returns this
 */
proto.m3api.CubeOfTrioMsg.prototype.setCubeId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 growth_context_id = 2;
 * @return {number}
 */
proto.m3api.CubeOfTrioMsg.prototype.getGrowthContextId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.m3api.CubeOfTrioMsg} returns this
 */
proto.m3api.CubeOfTrioMsg.prototype.setGrowthContextId = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 center_trio_id = 3;
 * @return {number}
 */
proto.m3api.CubeOfTrioMsg.prototype.getCenterTrioId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.m3api.CubeOfTrioMsg} returns this
 */
proto.m3api.CubeOfTrioMsg.prototype.setCenterTrioId = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * repeated int32 center_faces_trio_ids = 4;
 * @return {!Array<number>}
 */
proto.m3api.CubeOfTrioMsg.prototype.getCenterFacesTrioIdsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.m3api.CubeOfTrioMsg} returns this
 */
proto.m3api.CubeOfTrioMsg.prototype.setCenterFacesTrioIdsList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.m3api.CubeOfTrioMsg} returns this
 */
proto.m3api.CubeOfTrioMsg.prototype.addCenterFacesTrioIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.m3api.CubeOfTrioMsg} returns this
 */
proto.m3api.CubeOfTrioMsg.prototype.clearCenterFacesTrioIdsList = function() {
  return this.setCenterFacesTrioIdsList([]);
};


/**
 * repeated int32 middle_edges_trio_ids = 5;
 * @return {!Array<number>}
 */
proto.m3api.CubeOfTrioMsg.prototype.getMiddleEdgesTrioIdsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 5));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.m3api.CubeOfTrioMsg} returns this
 */
proto.m3api.CubeOfTrioMsg.prototype.setMiddleEdgesTrioIdsList = function(value) {
  return jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.m3api.CubeOfTrioMsg} returns this
 */
proto.m3api.CubeOfTrioMsg.prototype.addMiddleEdgesTrioIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.m3api.CubeOfTrioMsg} returns this
 */
proto.m3api.CubeOfTrioMsg.prototype.clearMiddleEdgesTrioIdsList = function() {
  return this.setMiddleEdgesTrioIdsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.m3api.RootPathNodeBuilderMsg.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.m3api.RootPathNodeBuilderMsg.prototype.toObject = function(opt_includeInstance) {
  return proto.m3api.RootPathNodeBuilderMsg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.m3api.RootPathNodeBuilderMsg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.m3api.RootPathNodeBuilderMsg.toObject = function(includeInstance, msg) {
  var f, obj = {
    cubeId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    trioId: jspb.Message.getFieldWithDefault(msg, 2, 0),
    interNodeBuildersList: jspb.Message.toObjectList(msg.getInterNodeBuildersList(),
    proto.m3api.IntermediatePathNodeBuilderMsg.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.m3api.RootPathNodeBuilderMsg}
 */
proto.m3api.RootPathNodeBuilderMsg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.m3api.RootPathNodeBuilderMsg;
  return proto.m3api.RootPathNodeBuilderMsg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.m3api.RootPathNodeBuilderMsg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.m3api.RootPathNodeBuilderMsg}
 */
proto.m3api.RootPathNodeBuilderMsg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCubeId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTrioId(value);
      break;
    case 3:
      var value = new proto.m3api.IntermediatePathNodeBuilderMsg;
      reader.readMessage(value,proto.m3api.IntermediatePathNodeBuilderMsg.deserializeBinaryFromReader);
      msg.addInterNodeBuilders(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.m3api.RootPathNodeBuilderMsg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.m3api.RootPathNodeBuilderMsg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.m3api.RootPathNodeBuilderMsg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.m3api.RootPathNodeBuilderMsg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCubeId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getTrioId();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getInterNodeBuildersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.m3api.IntermediatePathNodeBuilderMsg.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 cube_id = 1;
 * @return {number}
 */
proto.m3api.RootPathNodeBuilderMsg.prototype.getCubeId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.m3api.RootPathNodeBuilderMsg} returns this
 */
proto.m3api.RootPathNodeBuilderMsg.prototype.setCubeId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 trio_id = 2;
 * @return {number}
 */
proto.m3api.RootPathNodeBuilderMsg.prototype.getTrioId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.m3api.RootPathNodeBuilderMsg} returns this
 */
proto.m3api.RootPathNodeBuilderMsg.prototype.setTrioId = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * repeated IntermediatePathNodeBuilderMsg inter_node_builders = 3;
 * @return {!Array<!proto.m3api.IntermediatePathNodeBuilderMsg>}
 */
proto.m3api.RootPathNodeBuilderMsg.prototype.getInterNodeBuildersList = function() {
  return /** @type{!Array<!proto.m3api.IntermediatePathNodeBuilderMsg>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.m3api.IntermediatePathNodeBuilderMsg, 3));
};


/**
 * @param {!Array<!proto.m3api.IntermediatePathNodeBuilderMsg>} value
 * @return {!proto.m3api.RootPathNodeBuilderMsg} returns this
*/
proto.m3api.RootPathNodeBuilderMsg.prototype.setInterNodeBuildersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.m3api.IntermediatePathNodeBuilderMsg=} opt_value
 * @param {number=} opt_index
 * @return {!proto.m3api.IntermediatePathNodeBuilderMsg}
 */
proto.m3api.RootPathNodeBuilderMsg.prototype.addInterNodeBuilders = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.m3api.IntermediatePathNodeBuilderMsg, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.m3api.RootPathNodeBuilderMsg} returns this
 */
proto.m3api.RootPathNodeBuilderMsg.prototype.clearInterNodeBuildersList = function() {
  return this.setInterNodeBuildersList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.m3api.IntermediatePathNodeBuilderMsg.prototype.toObject = function(opt_includeInstance) {
  return proto.m3api.IntermediatePathNodeBuilderMsg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.m3api.IntermediatePathNodeBuilderMsg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.m3api.IntermediatePathNodeBuilderMsg.toObject = function(includeInstance, msg) {
  var f, obj = {
    cubeId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    trioId: jspb.Message.getFieldWithDefault(msg, 2, 0),
    link1ConnId: jspb.Message.getFieldWithDefault(msg, 3, 0),
    lastNodeBuilder1: (f = msg.getLastNodeBuilder1()) && proto.m3api.LastPathNodeBuilderMsg.toObject(includeInstance, f),
    link2ConnId: jspb.Message.getFieldWithDefault(msg, 5, 0),
    lastNodeBuilder2: (f = msg.getLastNodeBuilder2()) && proto.m3api.LastPathNodeBuilderMsg.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.m3api.IntermediatePathNodeBuilderMsg}
 */
proto.m3api.IntermediatePathNodeBuilderMsg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.m3api.IntermediatePathNodeBuilderMsg;
  return proto.m3api.IntermediatePathNodeBuilderMsg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.m3api.IntermediatePathNodeBuilderMsg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.m3api.IntermediatePathNodeBuilderMsg}
 */
proto.m3api.IntermediatePathNodeBuilderMsg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCubeId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTrioId(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readSint32());
      msg.setLink1ConnId(value);
      break;
    case 4:
      var value = new proto.m3api.LastPathNodeBuilderMsg;
      reader.readMessage(value,proto.m3api.LastPathNodeBuilderMsg.deserializeBinaryFromReader);
      msg.setLastNodeBuilder1(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readSint32());
      msg.setLink2ConnId(value);
      break;
    case 6:
      var value = new proto.m3api.LastPathNodeBuilderMsg;
      reader.readMessage(value,proto.m3api.LastPathNodeBuilderMsg.deserializeBinaryFromReader);
      msg.setLastNodeBuilder2(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.m3api.IntermediatePathNodeBuilderMsg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.m3api.IntermediatePathNodeBuilderMsg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.m3api.IntermediatePathNodeBuilderMsg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.m3api.IntermediatePathNodeBuilderMsg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCubeId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getTrioId();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getLink1ConnId();
  if (f !== 0) {
    writer.writeSint32(
      3,
      f
    );
  }
  f = message.getLastNodeBuilder1();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.m3api.LastPathNodeBuilderMsg.serializeBinaryToWriter
    );
  }
  f = message.getLink2ConnId();
  if (f !== 0) {
    writer.writeSint32(
      5,
      f
    );
  }
  f = message.getLastNodeBuilder2();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.m3api.LastPathNodeBuilderMsg.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 cube_id = 1;
 * @return {number}
 */
proto.m3api.IntermediatePathNodeBuilderMsg.prototype.getCubeId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.m3api.IntermediatePathNodeBuilderMsg} returns this
 */
proto.m3api.IntermediatePathNodeBuilderMsg.prototype.setCubeId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 trio_id = 2;
 * @return {number}
 */
proto.m3api.IntermediatePathNodeBuilderMsg.prototype.getTrioId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.m3api.IntermediatePathNodeBuilderMsg} returns this
 */
proto.m3api.IntermediatePathNodeBuilderMsg.prototype.setTrioId = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional sint32 link1_conn_id = 3;
 * @return {number}
 */
proto.m3api.IntermediatePathNodeBuilderMsg.prototype.getLink1ConnId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.m3api.IntermediatePathNodeBuilderMsg} returns this
 */
proto.m3api.IntermediatePathNodeBuilderMsg.prototype.setLink1ConnId = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional LastPathNodeBuilderMsg last_node_builder1 = 4;
 * @return {?proto.m3api.LastPathNodeBuilderMsg}
 */
proto.m3api.IntermediatePathNodeBuilderMsg.prototype.getLastNodeBuilder1 = function() {
  return /** @type{?proto.m3api.LastPathNodeBuilderMsg} */ (
    jspb.Message.getWrapperField(this, proto.m3api.LastPathNodeBuilderMsg, 4));
};


/**
 * @param {?proto.m3api.LastPathNodeBuilderMsg|undefined} value
 * @return {!proto.m3api.IntermediatePathNodeBuilderMsg} returns this
*/
proto.m3api.IntermediatePathNodeBuilderMsg.prototype.setLastNodeBuilder1 = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.m3api.IntermediatePathNodeBuilderMsg} returns this
 */
proto.m3api.IntermediatePathNodeBuilderMsg.prototype.clearLastNodeBuilder1 = function() {
  return this.setLastNodeBuilder1(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.m3api.IntermediatePathNodeBuilderMsg.prototype.hasLastNodeBuilder1 = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional sint32 link2_conn_id = 5;
 * @return {number}
 */
proto.m3api.IntermediatePathNodeBuilderMsg.prototype.getLink2ConnId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.m3api.IntermediatePathNodeBuilderMsg} returns this
 */
proto.m3api.IntermediatePathNodeBuilderMsg.prototype.setLink2ConnId = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional LastPathNodeBuilderMsg last_node_builder2 = 6;
 * @return {?proto.m3api.LastPathNodeBuilderMsg}
 */
proto.m3api.IntermediatePathNodeBuilderMsg.prototype.getLastNodeBuilder2 = function() {
  return /** @type{?proto.m3api.LastPathNodeBuilderMsg} */ (
    jspb.Message.getWrapperField(this, proto.m3api.LastPathNodeBuilderMsg, 6));
};


/**
 * @param {?proto.m3api.LastPathNodeBuilderMsg|undefined} value
 * @return {!proto.m3api.IntermediatePathNodeBuilderMsg} returns this
*/
proto.m3api.IntermediatePathNodeBuilderMsg.prototype.setLastNodeBuilder2 = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.m3api.IntermediatePathNodeBuilderMsg} returns this
 */
proto.m3api.IntermediatePathNodeBuilderMsg.prototype.clearLastNodeBuilder2 = function() {
  return this.setLastNodeBuilder2(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.m3api.IntermediatePathNodeBuilderMsg.prototype.hasLastNodeBuilder2 = function() {
  return jspb.Message.getField(this, 6) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.m3api.LastPathNodeBuilderMsg.prototype.toObject = function(opt_includeInstance) {
  return proto.m3api.LastPathNodeBuilderMsg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.m3api.LastPathNodeBuilderMsg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.m3api.LastPathNodeBuilderMsg.toObject = function(includeInstance, msg) {
  var f, obj = {
    cubeId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    trioId: jspb.Message.getFieldWithDefault(msg, 2, 0),
    nextMainConnId: jspb.Message.getFieldWithDefault(msg, 3, 0),
    nextInterConnId: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.m3api.LastPathNodeBuilderMsg}
 */
proto.m3api.LastPathNodeBuilderMsg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.m3api.LastPathNodeBuilderMsg;
  return proto.m3api.LastPathNodeBuilderMsg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.m3api.LastPathNodeBuilderMsg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.m3api.LastPathNodeBuilderMsg}
 */
proto.m3api.LastPathNodeBuilderMsg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCubeId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTrioId(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readSint32());
      msg.setNextMainConnId(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readSint32());
      msg.setNextInterConnId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.m3api.LastPathNodeBuilderMsg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.m3api.LastPathNodeBuilderMsg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.m3api.LastPathNodeBuilderMsg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.m3api.LastPathNodeBuilderMsg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCubeId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getTrioId();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getNextMainConnId();
  if (f !== 0) {
    writer.writeSint32(
      3,
      f
    );
  }
  f = message.getNextInterConnId();
  if (f !== 0) {
    writer.writeSint32(
      4,
      f
    );
  }
};


/**
 * optional int32 cube_id = 1;
 * @return {number}
 */
proto.m3api.LastPathNodeBuilderMsg.prototype.getCubeId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.m3api.LastPathNodeBuilderMsg} returns this
 */
proto.m3api.LastPathNodeBuilderMsg.prototype.setCubeId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 trio_id = 2;
 * @return {number}
 */
proto.m3api.LastPathNodeBuilderMsg.prototype.getTrioId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.m3api.LastPathNodeBuilderMsg} returns this
 */
proto.m3api.LastPathNodeBuilderMsg.prototype.setTrioId = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional sint32 next_main_conn_id = 3;
 * @return {number}
 */
proto.m3api.LastPathNodeBuilderMsg.prototype.getNextMainConnId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.m3api.LastPathNodeBuilderMsg} returns this
 */
proto.m3api.LastPathNodeBuilderMsg.prototype.setNextMainConnId = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional sint32 next_inter_conn_id = 4;
 * @return {number}
 */
proto.m3api.LastPathNodeBuilderMsg.prototype.getNextInterConnId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.m3api.LastPathNodeBuilderMsg} returns this
 */
proto.m3api.LastPathNodeBuilderMsg.prototype.setNextInterConnId = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.m3api.PointPackDataMsg.repeatedFields_ = [1,2,6,7,8,3,4,5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.m3api.PointPackDataMsg.prototype.toObject = function(opt_includeInstance) {
  return proto.m3api.PointPackDataMsg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.m3api.PointPackDataMsg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.m3api.PointPackDataMsg.toObject = function(includeInstance, msg) {
  var f, obj = {
    allConnectionsList: jspb.Message.toObjectList(msg.getAllConnectionsList(),
    proto.m3api.ConnectionMsg.toObject, includeInstance),
    allTriosList: jspb.Message.toObjectList(msg.getAllTriosList(),
    proto.m3api.TrioMsg.toObject, includeInstance),
    validNextTrioIdsList: (f = jspb.Message.getRepeatedField(msg, 6)) == null ? undefined : f,
    mod4PermutationsTrioIdsList: (f = jspb.Message.getRepeatedField(msg, 7)) == null ? undefined : f,
    mod8PermutationsTrioIdsList: (f = jspb.Message.getRepeatedField(msg, 8)) == null ? undefined : f,
    allGrowthContextsList: jspb.Message.toObjectList(msg.getAllGrowthContextsList(),
    proto.m3api.GrowthContextMsg.toObject, includeInstance),
    allCubesList: jspb.Message.toObjectList(msg.getAllCubesList(),
    proto.m3api.CubeOfTrioMsg.toObject, includeInstance),
    allPathNodeBuildersList: jspb.Message.toObjectList(msg.getAllPathNodeBuildersList(),
    proto.m3api.RootPathNodeBuilderMsg.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.m3api.PointPackDataMsg}
 */
proto.m3api.PointPackDataMsg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.m3api.PointPackDataMsg;
  return proto.m3api.PointPackDataMsg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.m3api.PointPackDataMsg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.m3api.PointPackDataMsg}
 */
proto.m3api.PointPackDataMsg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.m3api.ConnectionMsg;
      reader.readMessage(value,proto.m3api.ConnectionMsg.deserializeBinaryFromReader);
      msg.addAllConnections(value);
      break;
    case 2:
      var value = new proto.m3api.TrioMsg;
      reader.readMessage(value,proto.m3api.TrioMsg.deserializeBinaryFromReader);
      msg.addAllTrios(value);
      break;
    case 6:
      var value = /** @type {!Array<number>} */ (reader.readPackedInt32());
      msg.setValidNextTrioIdsList(value);
      break;
    case 7:
      var value = /** @type {!Array<number>} */ (reader.readPackedInt32());
      msg.setMod4PermutationsTrioIdsList(value);
      break;
    case 8:
      var value = /** @type {!Array<number>} */ (reader.readPackedInt32());
      msg.setMod8PermutationsTrioIdsList(value);
      break;
    case 3:
      var value = new proto.m3api.GrowthContextMsg;
      reader.readMessage(value,proto.m3api.GrowthContextMsg.deserializeBinaryFromReader);
      msg.addAllGrowthContexts(value);
      break;
    case 4:
      var value = new proto.m3api.CubeOfTrioMsg;
      reader.readMessage(value,proto.m3api.CubeOfTrioMsg.deserializeBinaryFromReader);
      msg.addAllCubes(value);
      break;
    case 5:
      var value = new proto.m3api.RootPathNodeBuilderMsg;
      reader.readMessage(value,proto.m3api.RootPathNodeBuilderMsg.deserializeBinaryFromReader);
      msg.addAllPathNodeBuilders(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.m3api.PointPackDataMsg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.m3api.PointPackDataMsg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.m3api.PointPackDataMsg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.m3api.PointPackDataMsg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAllConnectionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.m3api.ConnectionMsg.serializeBinaryToWriter
    );
  }
  f = message.getAllTriosList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.m3api.TrioMsg.serializeBinaryToWriter
    );
  }
  f = message.getValidNextTrioIdsList();
  if (f.length > 0) {
    writer.writePackedInt32(
      6,
      f
    );
  }
  f = message.getMod4PermutationsTrioIdsList();
  if (f.length > 0) {
    writer.writePackedInt32(
      7,
      f
    );
  }
  f = message.getMod8PermutationsTrioIdsList();
  if (f.length > 0) {
    writer.writePackedInt32(
      8,
      f
    );
  }
  f = message.getAllGrowthContextsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.m3api.GrowthContextMsg.serializeBinaryToWriter
    );
  }
  f = message.getAllCubesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.m3api.CubeOfTrioMsg.serializeBinaryToWriter
    );
  }
  f = message.getAllPathNodeBuildersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.m3api.RootPathNodeBuilderMsg.serializeBinaryToWriter
    );
  }
};


/**
 * repeated ConnectionMsg all_connections = 1;
 * @return {!Array<!proto.m3api.ConnectionMsg>}
 */
proto.m3api.PointPackDataMsg.prototype.getAllConnectionsList = function() {
  return /** @type{!Array<!proto.m3api.ConnectionMsg>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.m3api.ConnectionMsg, 1));
};


/**
 * @param {!Array<!proto.m3api.ConnectionMsg>} value
 * @return {!proto.m3api.PointPackDataMsg} returns this
*/
proto.m3api.PointPackDataMsg.prototype.setAllConnectionsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.m3api.ConnectionMsg=} opt_value
 * @param {number=} opt_index
 * @return {!proto.m3api.ConnectionMsg}
 */
proto.m3api.PointPackDataMsg.prototype.addAllConnections = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.m3api.ConnectionMsg, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.m3api.PointPackDataMsg} returns this
 */
proto.m3api.PointPackDataMsg.prototype.clearAllConnectionsList = function() {
  return this.setAllConnectionsList([]);
};


/**
 * repeated TrioMsg all_trios = 2;
 * @return {!Array<!proto.m3api.TrioMsg>}
 */
proto.m3api.PointPackDataMsg.prototype.getAllTriosList = function() {
  return /** @type{!Array<!proto.m3api.TrioMsg>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.m3api.TrioMsg, 2));
};


/**
 * @param {!Array<!proto.m3api.TrioMsg>} value
 * @return {!proto.m3api.PointPackDataMsg} returns this
*/
proto.m3api.PointPackDataMsg.prototype.setAllTriosList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.m3api.TrioMsg=} opt_value
 * @param {number=} opt_index
 * @return {!proto.m3api.TrioMsg}
 */
proto.m3api.PointPackDataMsg.prototype.addAllTrios = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.m3api.TrioMsg, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.m3api.PointPackDataMsg} returns this
 */
proto.m3api.PointPackDataMsg.prototype.clearAllTriosList = function() {
  return this.setAllTriosList([]);
};


/**
 * repeated int32 valid_next_trio_ids = 6;
 * @return {!Array<number>}
 */
proto.m3api.PointPackDataMsg.prototype.getValidNextTrioIdsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 6));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.m3api.PointPackDataMsg} returns this
 */
proto.m3api.PointPackDataMsg.prototype.setValidNextTrioIdsList = function(value) {
  return jspb.Message.setField(this, 6, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.m3api.PointPackDataMsg} returns this
 */
proto.m3api.PointPackDataMsg.prototype.addValidNextTrioIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 6, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.m3api.PointPackDataMsg} returns this
 */
proto.m3api.PointPackDataMsg.prototype.clearValidNextTrioIdsList = function() {
  return this.setValidNextTrioIdsList([]);
};


/**
 * repeated int32 mod4_permutations_trio_ids = 7;
 * @return {!Array<number>}
 */
proto.m3api.PointPackDataMsg.prototype.getMod4PermutationsTrioIdsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 7));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.m3api.PointPackDataMsg} returns this
 */
proto.m3api.PointPackDataMsg.prototype.setMod4PermutationsTrioIdsList = function(value) {
  return jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.m3api.PointPackDataMsg} returns this
 */
proto.m3api.PointPackDataMsg.prototype.addMod4PermutationsTrioIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.m3api.PointPackDataMsg} returns this
 */
proto.m3api.PointPackDataMsg.prototype.clearMod4PermutationsTrioIdsList = function() {
  return this.setMod4PermutationsTrioIdsList([]);
};


/**
 * repeated int32 mod8_permutations_trio_ids = 8;
 * @return {!Array<number>}
 */
proto.m3api.PointPackDataMsg.prototype.getMod8PermutationsTrioIdsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 8));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.m3api.PointPackDataMsg} returns this
 */
proto.m3api.PointPackDataMsg.prototype.setMod8PermutationsTrioIdsList = function(value) {
  return jspb.Message.setField(this, 8, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.m3api.PointPackDataMsg} returns this
 */
proto.m3api.PointPackDataMsg.prototype.addMod8PermutationsTrioIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 8, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.m3api.PointPackDataMsg} returns this
 */
proto.m3api.PointPackDataMsg.prototype.clearMod8PermutationsTrioIdsList = function() {
  return this.setMod8PermutationsTrioIdsList([]);
};


/**
 * repeated GrowthContextMsg all_growth_contexts = 3;
 * @return {!Array<!proto.m3api.GrowthContextMsg>}
 */
proto.m3api.PointPackDataMsg.prototype.getAllGrowthContextsList = function() {
  return /** @type{!Array<!proto.m3api.GrowthContextMsg>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.m3api.GrowthContextMsg, 3));
};


/**
 * @param {!Array<!proto.m3api.GrowthContextMsg>} value
 * @return {!proto.m3api.PointPackDataMsg} returns this
*/
proto.m3api.PointPackDataMsg.prototype.setAllGrowthContextsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.m3api.GrowthContextMsg=} opt_value
 * @param {number=} opt_index
 * @return {!proto.m3api.GrowthContextMsg}
 */
proto.m3api.PointPackDataMsg.prototype.addAllGrowthContexts = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.m3api.GrowthContextMsg, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.m3api.PointPackDataMsg} returns this
 */
proto.m3api.PointPackDataMsg.prototype.clearAllGrowthContextsList = function() {
  return this.setAllGrowthContextsList([]);
};


/**
 * repeated CubeOfTrioMsg all_cubes = 4;
 * @return {!Array<!proto.m3api.CubeOfTrioMsg>}
 */
proto.m3api.PointPackDataMsg.prototype.getAllCubesList = function() {
  return /** @type{!Array<!proto.m3api.CubeOfTrioMsg>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.m3api.CubeOfTrioMsg, 4));
};


/**
 * @param {!Array<!proto.m3api.CubeOfTrioMsg>} value
 * @return {!proto.m3api.PointPackDataMsg} returns this
*/
proto.m3api.PointPackDataMsg.prototype.setAllCubesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.m3api.CubeOfTrioMsg=} opt_value
 * @param {number=} opt_index
 * @return {!proto.m3api.CubeOfTrioMsg}
 */
proto.m3api.PointPackDataMsg.prototype.addAllCubes = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.m3api.CubeOfTrioMsg, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.m3api.PointPackDataMsg} returns this
 */
proto.m3api.PointPackDataMsg.prototype.clearAllCubesList = function() {
  return this.setAllCubesList([]);
};


/**
 * repeated RootPathNodeBuilderMsg all_path_node_builders = 5;
 * @return {!Array<!proto.m3api.RootPathNodeBuilderMsg>}
 */
proto.m3api.PointPackDataMsg.prototype.getAllPathNodeBuildersList = function() {
  return /** @type{!Array<!proto.m3api.RootPathNodeBuilderMsg>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.m3api.RootPathNodeBuilderMsg, 5));
};


/**
 * @param {!Array<!proto.m3api.RootPathNodeBuilderMsg>} value
 * @return {!proto.m3api.PointPackDataMsg} returns this
*/
proto.m3api.PointPackDataMsg.prototype.setAllPathNodeBuildersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.m3api.RootPathNodeBuilderMsg=} opt_value
 * @param {number=} opt_index
 * @return {!proto.m3api.RootPathNodeBuilderMsg}
 */
proto.m3api.PointPackDataMsg.prototype.addAllPathNodeBuilders = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.m3api.RootPathNodeBuilderMsg, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.m3api.PointPackDataMsg} returns this
 */
proto.m3api.PointPackDataMsg.prototype.clearAllPathNodeBuildersList = function() {
  return this.setAllPathNodeBuildersList([]);
};


goog.object.extend(exports, proto.m3api);
