// Code generated by protoc-gen-go. DO NOT EDIT.
// source: m3data.proto

package m3api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PointMsg struct {
	X                    int32    `protobuf:"zigzag32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"zigzag32,3,opt,name=y,proto3" json:"y,omitempty"`
	Z                    int32    `protobuf:"zigzag32,4,opt,name=z,proto3" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PointMsg) Reset()         { *m = PointMsg{} }
func (m *PointMsg) String() string { return proto.CompactTextString(m) }
func (*PointMsg) ProtoMessage()    {}
func (*PointMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc7573ead971cdcd, []int{0}
}

func (m *PointMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PointMsg.Unmarshal(m, b)
}
func (m *PointMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PointMsg.Marshal(b, m, deterministic)
}
func (m *PointMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PointMsg.Merge(m, src)
}
func (m *PointMsg) XXX_Size() int {
	return xxx_messageInfo_PointMsg.Size(m)
}
func (m *PointMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PointMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PointMsg proto.InternalMessageInfo

func (m *PointMsg) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *PointMsg) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *PointMsg) GetZ() int32 {
	if m != nil {
		return m.Z
	}
	return 0
}

type ConnectionMsg struct {
	ConnId               int32     `protobuf:"zigzag32,1,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	Vector               *PointMsg `protobuf:"bytes,2,opt,name=vector,proto3" json:"vector,omitempty"`
	Ds                   int64     `protobuf:"varint,3,opt,name=ds,proto3" json:"ds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ConnectionMsg) Reset()         { *m = ConnectionMsg{} }
func (m *ConnectionMsg) String() string { return proto.CompactTextString(m) }
func (*ConnectionMsg) ProtoMessage()    {}
func (*ConnectionMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc7573ead971cdcd, []int{1}
}

func (m *ConnectionMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionMsg.Unmarshal(m, b)
}
func (m *ConnectionMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionMsg.Marshal(b, m, deterministic)
}
func (m *ConnectionMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionMsg.Merge(m, src)
}
func (m *ConnectionMsg) XXX_Size() int {
	return xxx_messageInfo_ConnectionMsg.Size(m)
}
func (m *ConnectionMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionMsg proto.InternalMessageInfo

func (m *ConnectionMsg) GetConnId() int32 {
	if m != nil {
		return m.ConnId
	}
	return 0
}

func (m *ConnectionMsg) GetVector() *PointMsg {
	if m != nil {
		return m.Vector
	}
	return nil
}

func (m *ConnectionMsg) GetDs() int64 {
	if m != nil {
		return m.Ds
	}
	return 0
}

type TrioMsg struct {
	TrioId               int32    `protobuf:"varint,1,opt,name=trio_id,json=trioId,proto3" json:"trio_id,omitempty"`
	ConnIds              []int32  `protobuf:"zigzag32,2,rep,packed,name=conn_ids,json=connIds,proto3" json:"conn_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrioMsg) Reset()         { *m = TrioMsg{} }
func (m *TrioMsg) String() string { return proto.CompactTextString(m) }
func (*TrioMsg) ProtoMessage()    {}
func (*TrioMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc7573ead971cdcd, []int{2}
}

func (m *TrioMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrioMsg.Unmarshal(m, b)
}
func (m *TrioMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrioMsg.Marshal(b, m, deterministic)
}
func (m *TrioMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrioMsg.Merge(m, src)
}
func (m *TrioMsg) XXX_Size() int {
	return xxx_messageInfo_TrioMsg.Size(m)
}
func (m *TrioMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_TrioMsg.DiscardUnknown(m)
}

var xxx_messageInfo_TrioMsg proto.InternalMessageInfo

func (m *TrioMsg) GetTrioId() int32 {
	if m != nil {
		return m.TrioId
	}
	return 0
}

func (m *TrioMsg) GetConnIds() []int32 {
	if m != nil {
		return m.ConnIds
	}
	return nil
}

type GrowthContextMsg struct {
	GrowthContextId      int32    `protobuf:"varint,1,opt,name=growth_context_id,json=growthContextId,proto3" json:"growth_context_id,omitempty"`
	GrowthType           int32    `protobuf:"varint,2,opt,name=growth_type,json=growthType,proto3" json:"growth_type,omitempty"`
	GrowthIndex          int32    `protobuf:"varint,3,opt,name=growth_index,json=growthIndex,proto3" json:"growth_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrowthContextMsg) Reset()         { *m = GrowthContextMsg{} }
func (m *GrowthContextMsg) String() string { return proto.CompactTextString(m) }
func (*GrowthContextMsg) ProtoMessage()    {}
func (*GrowthContextMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc7573ead971cdcd, []int{3}
}

func (m *GrowthContextMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrowthContextMsg.Unmarshal(m, b)
}
func (m *GrowthContextMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrowthContextMsg.Marshal(b, m, deterministic)
}
func (m *GrowthContextMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrowthContextMsg.Merge(m, src)
}
func (m *GrowthContextMsg) XXX_Size() int {
	return xxx_messageInfo_GrowthContextMsg.Size(m)
}
func (m *GrowthContextMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_GrowthContextMsg.DiscardUnknown(m)
}

var xxx_messageInfo_GrowthContextMsg proto.InternalMessageInfo

func (m *GrowthContextMsg) GetGrowthContextId() int32 {
	if m != nil {
		return m.GrowthContextId
	}
	return 0
}

func (m *GrowthContextMsg) GetGrowthType() int32 {
	if m != nil {
		return m.GrowthType
	}
	return 0
}

func (m *GrowthContextMsg) GetGrowthIndex() int32 {
	if m != nil {
		return m.GrowthIndex
	}
	return 0
}

type CubeOfTrioMsg struct {
	CubeId               int32    `protobuf:"varint,1,opt,name=cube_id,json=cubeId,proto3" json:"cube_id,omitempty"`
	GrowthContextId      int32    `protobuf:"varint,2,opt,name=growth_context_id,json=growthContextId,proto3" json:"growth_context_id,omitempty"`
	CenterTrioId         int32    `protobuf:"varint,3,opt,name=center_trio_id,json=centerTrioId,proto3" json:"center_trio_id,omitempty"`
	CenterFacesTrioIds   []int32  `protobuf:"varint,4,rep,packed,name=center_faces_trio_ids,json=centerFacesTrioIds,proto3" json:"center_faces_trio_ids,omitempty"`
	MiddleEdgesTrioIds   []int32  `protobuf:"varint,5,rep,packed,name=middle_edges_trio_ids,json=middleEdgesTrioIds,proto3" json:"middle_edges_trio_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CubeOfTrioMsg) Reset()         { *m = CubeOfTrioMsg{} }
func (m *CubeOfTrioMsg) String() string { return proto.CompactTextString(m) }
func (*CubeOfTrioMsg) ProtoMessage()    {}
func (*CubeOfTrioMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc7573ead971cdcd, []int{4}
}

func (m *CubeOfTrioMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CubeOfTrioMsg.Unmarshal(m, b)
}
func (m *CubeOfTrioMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CubeOfTrioMsg.Marshal(b, m, deterministic)
}
func (m *CubeOfTrioMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CubeOfTrioMsg.Merge(m, src)
}
func (m *CubeOfTrioMsg) XXX_Size() int {
	return xxx_messageInfo_CubeOfTrioMsg.Size(m)
}
func (m *CubeOfTrioMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_CubeOfTrioMsg.DiscardUnknown(m)
}

var xxx_messageInfo_CubeOfTrioMsg proto.InternalMessageInfo

func (m *CubeOfTrioMsg) GetCubeId() int32 {
	if m != nil {
		return m.CubeId
	}
	return 0
}

func (m *CubeOfTrioMsg) GetGrowthContextId() int32 {
	if m != nil {
		return m.GrowthContextId
	}
	return 0
}

func (m *CubeOfTrioMsg) GetCenterTrioId() int32 {
	if m != nil {
		return m.CenterTrioId
	}
	return 0
}

func (m *CubeOfTrioMsg) GetCenterFacesTrioIds() []int32 {
	if m != nil {
		return m.CenterFacesTrioIds
	}
	return nil
}

func (m *CubeOfTrioMsg) GetMiddleEdgesTrioIds() []int32 {
	if m != nil {
		return m.MiddleEdgesTrioIds
	}
	return nil
}

type PathBuilderContextMsg struct {
	PathBuilderId        int32    `protobuf:"varint,1,opt,name=path_builder_id,json=pathBuilderId,proto3" json:"path_builder_id,omitempty"`
	GrowthContextId      int32    `protobuf:"varint,2,opt,name=growth_context_id,json=growthContextId,proto3" json:"growth_context_id,omitempty"`
	CubeId               int32    `protobuf:"varint,3,opt,name=cube_id,json=cubeId,proto3" json:"cube_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PathBuilderContextMsg) Reset()         { *m = PathBuilderContextMsg{} }
func (m *PathBuilderContextMsg) String() string { return proto.CompactTextString(m) }
func (*PathBuilderContextMsg) ProtoMessage()    {}
func (*PathBuilderContextMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc7573ead971cdcd, []int{5}
}

func (m *PathBuilderContextMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PathBuilderContextMsg.Unmarshal(m, b)
}
func (m *PathBuilderContextMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PathBuilderContextMsg.Marshal(b, m, deterministic)
}
func (m *PathBuilderContextMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PathBuilderContextMsg.Merge(m, src)
}
func (m *PathBuilderContextMsg) XXX_Size() int {
	return xxx_messageInfo_PathBuilderContextMsg.Size(m)
}
func (m *PathBuilderContextMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PathBuilderContextMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PathBuilderContextMsg proto.InternalMessageInfo

func (m *PathBuilderContextMsg) GetPathBuilderId() int32 {
	if m != nil {
		return m.PathBuilderId
	}
	return 0
}

func (m *PathBuilderContextMsg) GetGrowthContextId() int32 {
	if m != nil {
		return m.GrowthContextId
	}
	return 0
}

func (m *PathBuilderContextMsg) GetCubeId() int32 {
	if m != nil {
		return m.CubeId
	}
	return 0
}

type PathContextMsg struct {
	PathCtxId            int32    `protobuf:"varint,1,opt,name=path_ctx_id,json=pathCtxId,proto3" json:"path_ctx_id,omitempty"`
	GrowthContextId      int32    `protobuf:"varint,2,opt,name=growth_context_id,json=growthContextId,proto3" json:"growth_context_id,omitempty"`
	GrowthOffset         int32    `protobuf:"varint,3,opt,name=growth_offset,json=growthOffset,proto3" json:"growth_offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PathContextMsg) Reset()         { *m = PathContextMsg{} }
func (m *PathContextMsg) String() string { return proto.CompactTextString(m) }
func (*PathContextMsg) ProtoMessage()    {}
func (*PathContextMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc7573ead971cdcd, []int{6}
}

func (m *PathContextMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PathContextMsg.Unmarshal(m, b)
}
func (m *PathContextMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PathContextMsg.Marshal(b, m, deterministic)
}
func (m *PathContextMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PathContextMsg.Merge(m, src)
}
func (m *PathContextMsg) XXX_Size() int {
	return xxx_messageInfo_PathContextMsg.Size(m)
}
func (m *PathContextMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PathContextMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PathContextMsg proto.InternalMessageInfo

func (m *PathContextMsg) GetPathCtxId() int32 {
	if m != nil {
		return m.PathCtxId
	}
	return 0
}

func (m *PathContextMsg) GetGrowthContextId() int32 {
	if m != nil {
		return m.GrowthContextId
	}
	return 0
}

func (m *PathContextMsg) GetGrowthOffset() int32 {
	if m != nil {
		return m.GrowthOffset
	}
	return 0
}

type PathNodeMsg struct {
	PathNodeId           int64     `protobuf:"varint,1,opt,name=path_node_id,json=pathNodeId,proto3" json:"path_node_id,omitempty"`
	PathCtxId            int32     `protobuf:"varint,2,opt,name=path_ctx_id,json=pathCtxId,proto3" json:"path_ctx_id,omitempty"`
	Point                *PointMsg `protobuf:"bytes,3,opt,name=point,proto3" json:"point,omitempty"`
	D                    int64     `protobuf:"varint,4,opt,name=d,proto3" json:"d,omitempty"`
	PathBuilderId        int32     `protobuf:"varint,5,opt,name=path_builder_id,json=pathBuilderId,proto3" json:"path_builder_id,omitempty"`
	TrioId               int32     `protobuf:"varint,6,opt,name=trio_id,json=trioId,proto3" json:"trio_id,omitempty"`
	ConnectionMask       uint32    `protobuf:"varint,7,opt,name=connection_mask,json=connectionMask,proto3" json:"connection_mask,omitempty"`
	LinkedPathNodeIds    []int64   `protobuf:"varint,8,rep,packed,name=linked_path_node_ids,json=linkedPathNodeIds,proto3" json:"linked_path_node_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PathNodeMsg) Reset()         { *m = PathNodeMsg{} }
func (m *PathNodeMsg) String() string { return proto.CompactTextString(m) }
func (*PathNodeMsg) ProtoMessage()    {}
func (*PathNodeMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc7573ead971cdcd, []int{7}
}

func (m *PathNodeMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PathNodeMsg.Unmarshal(m, b)
}
func (m *PathNodeMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PathNodeMsg.Marshal(b, m, deterministic)
}
func (m *PathNodeMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PathNodeMsg.Merge(m, src)
}
func (m *PathNodeMsg) XXX_Size() int {
	return xxx_messageInfo_PathNodeMsg.Size(m)
}
func (m *PathNodeMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PathNodeMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PathNodeMsg proto.InternalMessageInfo

func (m *PathNodeMsg) GetPathNodeId() int64 {
	if m != nil {
		return m.PathNodeId
	}
	return 0
}

func (m *PathNodeMsg) GetPathCtxId() int32 {
	if m != nil {
		return m.PathCtxId
	}
	return 0
}

func (m *PathNodeMsg) GetPoint() *PointMsg {
	if m != nil {
		return m.Point
	}
	return nil
}

func (m *PathNodeMsg) GetD() int64 {
	if m != nil {
		return m.D
	}
	return 0
}

func (m *PathNodeMsg) GetPathBuilderId() int32 {
	if m != nil {
		return m.PathBuilderId
	}
	return 0
}

func (m *PathNodeMsg) GetTrioId() int32 {
	if m != nil {
		return m.TrioId
	}
	return 0
}

func (m *PathNodeMsg) GetConnectionMask() uint32 {
	if m != nil {
		return m.ConnectionMask
	}
	return 0
}

func (m *PathNodeMsg) GetLinkedPathNodeIds() []int64 {
	if m != nil {
		return m.LinkedPathNodeIds
	}
	return nil
}

func init() {
	proto.RegisterType((*PointMsg)(nil), "m3api.PointMsg")
	proto.RegisterType((*ConnectionMsg)(nil), "m3api.ConnectionMsg")
	proto.RegisterType((*TrioMsg)(nil), "m3api.TrioMsg")
	proto.RegisterType((*GrowthContextMsg)(nil), "m3api.GrowthContextMsg")
	proto.RegisterType((*CubeOfTrioMsg)(nil), "m3api.CubeOfTrioMsg")
	proto.RegisterType((*PathBuilderContextMsg)(nil), "m3api.PathBuilderContextMsg")
	proto.RegisterType((*PathContextMsg)(nil), "m3api.PathContextMsg")
	proto.RegisterType((*PathNodeMsg)(nil), "m3api.PathNodeMsg")
}

func init() {
	proto.RegisterFile("m3data.proto", fileDescriptor_cc7573ead971cdcd)
}

var fileDescriptor_cc7573ead971cdcd = []byte{
	// 547 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcb, 0x8e, 0xd3, 0x40,
	0x10, 0x94, 0xed, 0x75, 0x12, 0x3a, 0x2f, 0x62, 0xb1, 0xc2, 0x5c, 0xc0, 0x98, 0xc7, 0x46, 0x1c,
	0x82, 0x20, 0x5c, 0xb9, 0x10, 0x01, 0xf2, 0x61, 0xd9, 0x68, 0x94, 0xbb, 0xe5, 0x78, 0x26, 0x89,
	0x95, 0x64, 0xc6, 0xf2, 0x4c, 0xc0, 0xd9, 0x1b, 0x88, 0xff, 0xe0, 0xd7, 0xf8, 0x14, 0x34, 0x8f,
	0x24, 0xc3, 0x2a, 0x97, 0x3d, 0x76, 0x75, 0xf5, 0x54, 0x75, 0x59, 0x6d, 0xe8, 0x6c, 0xc7, 0x38,
	0x13, 0xd9, 0xa8, 0xac, 0x98, 0x60, 0x81, 0xbf, 0x1d, 0x67, 0x65, 0x11, 0x7f, 0x80, 0xd6, 0x94,
	0x15, 0x54, 0x5c, 0xf3, 0x65, 0xd0, 0x01, 0xa7, 0x0e, 0xdd, 0xc8, 0x19, 0x0e, 0x90, 0x53, 0xcb,
	0x6a, 0x1f, 0x7a, 0xba, 0xda, 0xcb, 0xea, 0x36, 0xbc, 0xd0, 0xd5, 0x6d, 0x9c, 0x41, 0x77, 0xc2,
	0x28, 0x25, 0xb9, 0x28, 0x18, 0x95, 0xa3, 0x8f, 0xa1, 0x99, 0x33, 0x4a, 0xd3, 0x02, 0x87, 0x8e,
	0x22, 0x35, 0x64, 0x99, 0xe0, 0xe0, 0x0a, 0x1a, 0xdf, 0x49, 0x2e, 0x58, 0xa5, 0x1e, 0x6e, 0xbf,
	0xef, 0x8f, 0x94, 0xee, 0xe8, 0x20, 0x8a, 0x4c, 0x3b, 0xe8, 0x81, 0x8b, 0xb9, 0xd2, 0xf3, 0x90,
	0x8b, 0x79, 0xfc, 0x11, 0x9a, 0xb3, 0xaa, 0x60, 0xe6, 0x71, 0x51, 0x15, 0xec, 0xf0, 0xb8, 0x8f,
	0x1a, 0xb2, 0x4c, 0x70, 0xf0, 0x04, 0x5a, 0x46, 0x95, 0x87, 0x6e, 0xe4, 0x0d, 0x07, 0xa8, 0xa9,
	0x65, 0x79, 0xfc, 0xcb, 0x81, 0x87, 0x5f, 0x2b, 0xf6, 0x43, 0xac, 0x26, 0x8c, 0x0a, 0x52, 0xab,
	0x05, 0xdf, 0xc0, 0x60, 0xa9, 0xb0, 0x34, 0xd7, 0xe0, 0xe9, 0xc9, 0xfe, 0xd2, 0x26, 0x27, 0x38,
	0x78, 0x06, 0x6d, 0xc3, 0x15, 0xfb, 0x92, 0x28, 0xf7, 0x3e, 0x02, 0x0d, 0xcd, 0xf6, 0x25, 0x09,
	0x9e, 0x43, 0xc7, 0x10, 0x0a, 0x8a, 0x49, 0xad, 0xac, 0xfb, 0xc8, 0x0c, 0x25, 0x12, 0x8a, 0xff,
	0x3a, 0xd0, 0x9d, 0xec, 0xe6, 0xe4, 0x66, 0x61, 0xad, 0x92, 0xef, 0xe6, 0xc4, 0x5a, 0x45, 0x96,
	0x09, 0x3e, 0x6f, 0xcd, 0x3d, 0x6f, 0xed, 0x25, 0xf4, 0x72, 0x42, 0x05, 0xa9, 0xd2, 0x43, 0x2c,
	0x5a, 0xbb, 0xa3, 0xd1, 0x99, 0x0e, 0xe7, 0x1d, 0x5c, 0x1a, 0xd6, 0x22, 0xcb, 0x09, 0x3f, 0x70,
	0x79, 0x78, 0x11, 0x79, 0x43, 0x1f, 0x05, 0xba, 0xf9, 0x45, 0xf6, 0xf4, 0x04, 0x97, 0x23, 0xdb,
	0x02, 0xe3, 0x0d, 0x49, 0x09, 0x5e, 0xda, 0x23, 0xbe, 0x1e, 0xd1, 0xcd, 0xcf, 0xb2, 0x67, 0x46,
	0xe2, 0xdf, 0x0e, 0x5c, 0x4e, 0x33, 0xb1, 0xfa, 0xb4, 0x2b, 0x36, 0x98, 0x54, 0x56, 0xd8, 0xaf,
	0xa1, 0x5f, 0x66, 0x62, 0x95, 0xce, 0x75, 0xe7, 0xb4, 0x72, 0xb7, 0x3c, 0xf1, 0xef, 0xb9, 0xb9,
	0x15, 0x9f, 0x67, 0xc7, 0x17, 0xff, 0x74, 0xa0, 0x27, 0x6d, 0x58, 0xfa, 0x4f, 0xa1, 0xad, 0xf4,
	0x73, 0x51, 0x9f, 0xb4, 0x1f, 0x48, 0x68, 0x22, 0xea, 0x7b, 0xea, 0xbe, 0x80, 0xae, 0xe1, 0xb2,
	0xc5, 0x82, 0x13, 0x71, 0x08, 0x5c, 0x83, 0x37, 0x0a, 0x8b, 0xff, 0xb8, 0xd0, 0x96, 0x1e, 0xbe,
	0x31, 0x4c, 0xa4, 0x81, 0x08, 0x3a, 0xca, 0x00, 0x65, 0xf8, 0xf8, 0xc1, 0x3d, 0x04, 0xa5, 0xa1,
	0x24, 0xf8, 0xae, 0x45, 0xf7, 0xae, 0xc5, 0x57, 0xe0, 0x97, 0xf2, 0x4e, 0x94, 0xdc, 0x99, 0xdb,
	0xd1, 0x5d, 0x79, 0x9b, 0x58, 0xdd, 0xa6, 0x87, 0x1c, 0x7c, 0x2e, 0x77, 0xff, 0x5c, 0xee, 0xd6,
	0x55, 0x35, 0xfe, 0xbb, 0xaa, 0x2b, 0xe8, 0xe7, 0xc7, 0xe3, 0x4e, 0xb7, 0x19, 0x5f, 0x87, 0xcd,
	0xc8, 0x19, 0x76, 0x51, 0xef, 0x04, 0x5f, 0x67, 0x7c, 0x1d, 0xbc, 0x85, 0x47, 0x9b, 0x82, 0xae,
	0x09, 0x4e, 0xed, 0x3d, 0x79, 0xd8, 0x8a, 0xbc, 0xa1, 0x87, 0x06, 0xba, 0x37, 0x3d, 0xae, 0xcb,
	0xe7, 0x0d, 0xf5, 0xeb, 0x19, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x0a, 0xd0, 0x22, 0x8a,
	0x04, 0x00, 0x00,
}
