// Code generated by protoc-gen-go. DO NOT EDIT.
// source: m3env.proto

package m3api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EnvMsg struct {
	EnvId                int32    `protobuf:"varint,1,opt,name=env_id,json=envId,proto3" json:"env_id" query:"env_id"`
	SchemaName           string   `protobuf:"bytes,2,opt,name=schema_name,json=schemaName,proto3" json:"schema_name" query:"schema_name"`
	SchemaSize           int64    `protobuf:"varint,3,opt,name=schema_size,json=schemaSize,proto3" json:"schema_size" query:"schema_size"`
	SchemaSizePercent    float32  `protobuf:"fixed32,4,opt,name=schema_size_percent,json=schemaSizePercent,proto3" json:"schema_size_percent,omitempty" query:"-"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" query:"-"`
	XXX_unrecognized     []byte   `json:"-" query:"-"`
	XXX_sizecache        int32    `json:"-" query:"-"`
}

func (m *EnvMsg) Reset()         { *m = EnvMsg{} }
func (m *EnvMsg) String() string { return proto.CompactTextString(m) }
func (*EnvMsg) ProtoMessage()    {}
func (*EnvMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f1c3839dc76096c, []int{0}
}

func (m *EnvMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnvMsg.Unmarshal(m, b)
}
func (m *EnvMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnvMsg.Marshal(b, m, deterministic)
}
func (m *EnvMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnvMsg.Merge(m, src)
}
func (m *EnvMsg) XXX_Size() int {
	return xxx_messageInfo_EnvMsg.Size(m)
}
func (m *EnvMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_EnvMsg.DiscardUnknown(m)
}

var xxx_messageInfo_EnvMsg proto.InternalMessageInfo

func (m *EnvMsg) GetEnvId() int32 {
	if m != nil {
		return m.EnvId
	}
	return 0
}

func (m *EnvMsg) GetSchemaName() string {
	if m != nil {
		return m.SchemaName
	}
	return ""
}

func (m *EnvMsg) GetSchemaSize() int64 {
	if m != nil {
		return m.SchemaSize
	}
	return 0
}

func (m *EnvMsg) GetSchemaSizePercent() float32 {
	if m != nil {
		return m.SchemaSizePercent
	}
	return 0
}

type EnvListMsg struct {
	Envs                 []*EnvMsg `protobuf:"bytes,1,rep,name=envs,proto3" json:"envs,omitempty" query:"-"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-" query:"-"`
	XXX_unrecognized     []byte    `json:"-" query:"-"`
	XXX_sizecache        int32     `json:"-" query:"-"`
}

func (m *EnvListMsg) Reset()         { *m = EnvListMsg{} }
func (m *EnvListMsg) String() string { return proto.CompactTextString(m) }
func (*EnvListMsg) ProtoMessage()    {}
func (*EnvListMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f1c3839dc76096c, []int{1}
}

func (m *EnvListMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnvListMsg.Unmarshal(m, b)
}
func (m *EnvListMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnvListMsg.Marshal(b, m, deterministic)
}
func (m *EnvListMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnvListMsg.Merge(m, src)
}
func (m *EnvListMsg) XXX_Size() int {
	return xxx_messageInfo_EnvListMsg.Size(m)
}
func (m *EnvListMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_EnvListMsg.DiscardUnknown(m)
}

var xxx_messageInfo_EnvListMsg proto.InternalMessageInfo

func (m *EnvListMsg) GetEnvs() []*EnvMsg {
	if m != nil {
		return m.Envs
	}
	return nil
}

func init() {
	proto.RegisterType((*EnvMsg)(nil), "m3api.EnvMsg")
	proto.RegisterType((*EnvListMsg)(nil), "m3api.EnvListMsg")
}

func init() {
	proto.RegisterFile("m3env.proto", fileDescriptor_1f1c3839dc76096c)
}

var fileDescriptor_1f1c3839dc76096c = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xcf, 0xbf, 0x6a, 0xc3, 0x30,
	0x10, 0xc7, 0x71, 0xe4, 0x7f, 0xd0, 0x33, 0x1d, 0xaa, 0x52, 0xd0, 0x56, 0xd5, 0x93, 0x26, 0x15,
	0xea, 0x67, 0xf0, 0x50, 0x68, 0x4b, 0x51, 0x1e, 0xc0, 0x28, 0xf6, 0x91, 0x68, 0xd0, 0xd9, 0x58,
	0x46, 0x83, 0xdf, 0x22, 0x6f, 0x1c, 0x62, 0x13, 0xe2, 0xf5, 0x7e, 0x9f, 0xe1, 0x7b, 0x50, 0xfa,
	0x1a, 0x29, 0xea, 0x71, 0x1a, 0xe6, 0x81, 0xe7, 0xbe, 0xb6, 0xa3, 0xab, 0x2e, 0x0c, 0x8a, 0x86,
	0xe2, 0x6f, 0x38, 0xf1, 0x37, 0x28, 0x90, 0x62, 0xeb, 0x7a, 0xc1, 0x24, 0x53, 0xb9, 0xc9, 0x91,
	0xe2, 0x77, 0xcf, 0xdf, 0xa1, 0x0c, 0xdd, 0x19, 0xbd, 0x6d, 0xc9, 0x7a, 0x14, 0x89, 0x64, 0xea,
	0xc9, 0xc0, 0x76, 0xfa, 0xb3, 0x1e, 0x77, 0x20, 0xb8, 0x05, 0x45, 0x2a, 0x99, 0x4a, 0xef, 0xe0,
	0xe0, 0x16, 0xe4, 0x1a, 0x5e, 0x77, 0xa0, 0x1d, 0x71, 0xea, 0x90, 0x66, 0x91, 0x49, 0xa6, 0x12,
	0xf3, 0xf2, 0x80, 0xff, 0xdb, 0x50, 0x7d, 0x02, 0x34, 0x14, 0x7f, 0x5c, 0x98, 0x6f, 0x59, 0x1f,
	0x90, 0x21, 0xc5, 0x20, 0x98, 0x4c, 0x55, 0xf9, 0xf5, 0xac, 0xd7, 0x6e, 0xbd, 0x35, 0x9b, 0x75,
	0x3a, 0x16, 0xeb, 0x4b, 0xf5, 0x35, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x3f, 0xe4, 0x7f, 0xe1, 0x00,
	0x00, 0x00,
}
