// Code generated by protoc-gen-go. DO NOT EDIT.
// source: m3path.proto

package m3api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PathContextMsg struct {
	PathCtxId            int32     `protobuf:"varint,1,opt,name=path_ctx_id,json=pathCtxId,proto3" json:"path_ctx_id,omitempty"`
	GrowthContextId      int32     `protobuf:"varint,2,opt,name=growth_context_id,json=growthContextId,proto3" json:"growth_context_id,omitempty"`
	GrowthOffset         int32     `protobuf:"varint,3,opt,name=growth_offset,json=growthOffset,proto3" json:"growth_offset,omitempty"`
	Center               *PointMsg `protobuf:"bytes,4,opt,name=center,proto3" json:"center,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PathContextMsg) Reset()         { *m = PathContextMsg{} }
func (m *PathContextMsg) String() string { return proto.CompactTextString(m) }
func (*PathContextMsg) ProtoMessage()    {}
func (*PathContextMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8f5151eb02dd926, []int{0}
}

func (m *PathContextMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PathContextMsg.Unmarshal(m, b)
}
func (m *PathContextMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PathContextMsg.Marshal(b, m, deterministic)
}
func (m *PathContextMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PathContextMsg.Merge(m, src)
}
func (m *PathContextMsg) XXX_Size() int {
	return xxx_messageInfo_PathContextMsg.Size(m)
}
func (m *PathContextMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PathContextMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PathContextMsg proto.InternalMessageInfo

func (m *PathContextMsg) GetPathCtxId() int32 {
	if m != nil {
		return m.PathCtxId
	}
	return 0
}

func (m *PathContextMsg) GetGrowthContextId() int32 {
	if m != nil {
		return m.GrowthContextId
	}
	return 0
}

func (m *PathContextMsg) GetGrowthOffset() int32 {
	if m != nil {
		return m.GrowthOffset
	}
	return 0
}

func (m *PathContextMsg) GetCenter() *PointMsg {
	if m != nil {
		return m.Center
	}
	return nil
}

type PathNodeMsg struct {
	PathNodeId           int64     `protobuf:"varint,1,opt,name=path_node_id,json=pathNodeId,proto3" json:"path_node_id,omitempty"`
	PathCtxId            int32     `protobuf:"varint,2,opt,name=path_ctx_id,json=pathCtxId,proto3" json:"path_ctx_id,omitempty"`
	Point                *PointMsg `protobuf:"bytes,3,opt,name=point,proto3" json:"point,omitempty"`
	D                    int64     `protobuf:"varint,4,opt,name=d,proto3" json:"d,omitempty"`
	TrioId               int32     `protobuf:"varint,5,opt,name=trio_id,json=trioId,proto3" json:"trio_id,omitempty"`
	ConnectionMask       uint32    `protobuf:"varint,6,opt,name=connection_mask,json=connectionMask,proto3" json:"connection_mask,omitempty"`
	LinkedPathNodeIds    []int64   `protobuf:"varint,7,rep,packed,name=linked_path_node_ids,json=linkedPathNodeIds,proto3" json:"linked_path_node_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PathNodeMsg) Reset()         { *m = PathNodeMsg{} }
func (m *PathNodeMsg) String() string { return proto.CompactTextString(m) }
func (*PathNodeMsg) ProtoMessage()    {}
func (*PathNodeMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8f5151eb02dd926, []int{1}
}

func (m *PathNodeMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PathNodeMsg.Unmarshal(m, b)
}
func (m *PathNodeMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PathNodeMsg.Marshal(b, m, deterministic)
}
func (m *PathNodeMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PathNodeMsg.Merge(m, src)
}
func (m *PathNodeMsg) XXX_Size() int {
	return xxx_messageInfo_PathNodeMsg.Size(m)
}
func (m *PathNodeMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PathNodeMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PathNodeMsg proto.InternalMessageInfo

func (m *PathNodeMsg) GetPathNodeId() int64 {
	if m != nil {
		return m.PathNodeId
	}
	return 0
}

func (m *PathNodeMsg) GetPathCtxId() int32 {
	if m != nil {
		return m.PathCtxId
	}
	return 0
}

func (m *PathNodeMsg) GetPoint() *PointMsg {
	if m != nil {
		return m.Point
	}
	return nil
}

func (m *PathNodeMsg) GetD() int64 {
	if m != nil {
		return m.D
	}
	return 0
}

func (m *PathNodeMsg) GetTrioId() int32 {
	if m != nil {
		return m.TrioId
	}
	return 0
}

func (m *PathNodeMsg) GetConnectionMask() uint32 {
	if m != nil {
		return m.ConnectionMask
	}
	return 0
}

func (m *PathNodeMsg) GetLinkedPathNodeIds() []int64 {
	if m != nil {
		return m.LinkedPathNodeIds
	}
	return nil
}

func init() {
	proto.RegisterType((*PathContextMsg)(nil), "m3api.PathContextMsg")
	proto.RegisterType((*PathNodeMsg)(nil), "m3api.PathNodeMsg")
}

func init() {
	proto.RegisterFile("m3path.proto", fileDescriptor_e8f5151eb02dd926)
}

var fileDescriptor_e8f5151eb02dd926 = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xdf, 0x4a, 0xc3, 0x30,
	0x14, 0xc6, 0xc9, 0x6a, 0x3b, 0x3c, 0xeb, 0x36, 0x16, 0x04, 0x8b, 0x17, 0x52, 0x26, 0xb2, 0xe2,
	0xc5, 0x04, 0xfb, 0x08, 0xbb, 0xea, 0xc5, 0x74, 0xe4, 0x05, 0x4a, 0x6d, 0xb2, 0x2d, 0xcc, 0x26,
	0xa5, 0x39, 0x60, 0x9f, 0xc9, 0x17, 0xf4, 0x56, 0x92, 0xd4, 0x3f, 0x0c, 0x2f, 0xf3, 0x7d, 0xdf,
	0x39, 0xf9, 0x7d, 0x09, 0xc4, 0x4d, 0xde, 0x56, 0x78, 0x5c, 0xb7, 0x9d, 0x46, 0x4d, 0xc3, 0x26,
	0xaf, 0x5a, 0x79, 0x33, 0x6d, 0xf2, 0x56, 0x4b, 0x85, 0x5e, 0x5d, 0x7e, 0x10, 0x98, 0xed, 0x2a,
	0x3c, 0x6e, 0xb4, 0x42, 0xd1, 0xe3, 0xd6, 0x1c, 0xe8, 0x2d, 0x4c, 0xec, 0x58, 0x59, 0x63, 0x5f,
	0x4a, 0x9e, 0x90, 0x94, 0x64, 0x21, 0xbb, 0xb4, 0xd2, 0x06, 0xfb, 0x82, 0xd3, 0x07, 0x58, 0x1c,
	0x3a, 0xfd, 0x6e, 0x13, 0x7e, 0xc8, 0xa6, 0x46, 0x2e, 0x35, 0xf7, 0xc6, 0xb0, 0xac, 0xe0, 0xf4,
	0x0e, 0xa6, 0x43, 0x56, 0xef, 0xf7, 0x46, 0x60, 0x12, 0xb8, 0x5c, 0xec, 0xc5, 0x17, 0xa7, 0xd1,
	0x15, 0x44, 0xb5, 0x50, 0x28, 0xba, 0xe4, 0x22, 0x25, 0xd9, 0xe4, 0x69, 0xbe, 0x76, 0xa8, 0xeb,
	0x9d, 0xe5, 0xdc, 0x9a, 0x03, 0x1b, 0xec, 0xe5, 0x27, 0x81, 0x89, 0x85, 0x7d, 0xd6, 0x5c, 0x58,
	0xd2, 0x14, 0x62, 0x47, 0xaa, 0x34, 0x17, 0xdf, 0xa8, 0x01, 0x83, 0x76, 0x88, 0x14, 0xfc, 0xbc,
	0xcb, 0xe8, 0xbc, 0xcb, 0x3d, 0x84, 0xee, 0x35, 0x1c, 0xd7, 0x3f, 0x37, 0x7b, 0x97, 0xc6, 0x40,
	0xb8, 0x83, 0x0b, 0x18, 0xe1, 0xf4, 0x1a, 0xc6, 0xd8, 0x49, 0x6d, 0x17, 0x86, 0x6e, 0x61, 0x64,
	0x8f, 0x05, 0xa7, 0x2b, 0x98, 0xd7, 0x5a, 0x29, 0x51, 0xa3, 0xd4, 0xaa, 0x6c, 0x2a, 0x73, 0x4a,
	0xa2, 0x94, 0x64, 0x53, 0x36, 0xfb, 0x95, 0xb7, 0x95, 0x39, 0xd1, 0x47, 0xb8, 0x7a, 0x93, 0xea,
	0x24, 0x78, 0xf9, 0x97, 0xdf, 0x24, 0xe3, 0x34, 0xc8, 0x02, 0xb6, 0xf0, 0xde, 0xee, 0xa7, 0x86,
	0x79, 0x8d, 0xdc, 0x6f, 0xe5, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x15, 0x76, 0x18, 0xd3,
	0x01, 0x00, 0x00,
}
