// Code generated by protoc-gen-go. DO NOT EDIT.
// source: m3path.proto

package m3api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PathContextRequestMsg struct {
	GrowthType           int32    `protobuf:"varint,1,opt,name=growth_type,json=growthType,proto3" json:"growth_type,omitempty"`
	GrowthIndex          int32    `protobuf:"varint,2,opt,name=growth_index,json=growthIndex,proto3" json:"growth_index,omitempty"`
	GrowthOffset         int32    `protobuf:"varint,3,opt,name=growth_offset,json=growthOffset,proto3" json:"growth_offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PathContextRequestMsg) Reset()         { *m = PathContextRequestMsg{} }
func (m *PathContextRequestMsg) String() string { return proto.CompactTextString(m) }
func (*PathContextRequestMsg) ProtoMessage()    {}
func (*PathContextRequestMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8f5151eb02dd926, []int{0}
}

func (m *PathContextRequestMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PathContextRequestMsg.Unmarshal(m, b)
}
func (m *PathContextRequestMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PathContextRequestMsg.Marshal(b, m, deterministic)
}
func (m *PathContextRequestMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PathContextRequestMsg.Merge(m, src)
}
func (m *PathContextRequestMsg) XXX_Size() int {
	return xxx_messageInfo_PathContextRequestMsg.Size(m)
}
func (m *PathContextRequestMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PathContextRequestMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PathContextRequestMsg proto.InternalMessageInfo

func (m *PathContextRequestMsg) GetGrowthType() int32 {
	if m != nil {
		return m.GrowthType
	}
	return 0
}

func (m *PathContextRequestMsg) GetGrowthIndex() int32 {
	if m != nil {
		return m.GrowthIndex
	}
	return 0
}

func (m *PathContextRequestMsg) GetGrowthOffset() int32 {
	if m != nil {
		return m.GrowthOffset
	}
	return 0
}

type PathNodeMsg struct {
	PathNodeId           int64     `protobuf:"varint,1,opt,name=path_node_id,json=pathNodeId,proto3" json:"path_node_id,omitempty"`
	Point                *PointMsg `protobuf:"bytes,2,opt,name=point,proto3" json:"point,omitempty"`
	D                    int32     `protobuf:"varint,3,opt,name=d,proto3" json:"d,omitempty"`
	TrioId               int32     `protobuf:"varint,4,opt,name=trio_id,json=trioId,proto3" json:"trio_id,omitempty"`
	ConnectionMask       uint32    `protobuf:"varint,5,opt,name=connection_mask,json=connectionMask,proto3" json:"connection_mask,omitempty"`
	LinkedPathNodeIds    []int64   `protobuf:"varint,6,rep,packed,name=linked_path_node_ids,json=linkedPathNodeIds,proto3" json:"linked_path_node_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PathNodeMsg) Reset()         { *m = PathNodeMsg{} }
func (m *PathNodeMsg) String() string { return proto.CompactTextString(m) }
func (*PathNodeMsg) ProtoMessage()    {}
func (*PathNodeMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8f5151eb02dd926, []int{1}
}

func (m *PathNodeMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PathNodeMsg.Unmarshal(m, b)
}
func (m *PathNodeMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PathNodeMsg.Marshal(b, m, deterministic)
}
func (m *PathNodeMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PathNodeMsg.Merge(m, src)
}
func (m *PathNodeMsg) XXX_Size() int {
	return xxx_messageInfo_PathNodeMsg.Size(m)
}
func (m *PathNodeMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PathNodeMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PathNodeMsg proto.InternalMessageInfo

func (m *PathNodeMsg) GetPathNodeId() int64 {
	if m != nil {
		return m.PathNodeId
	}
	return 0
}

func (m *PathNodeMsg) GetPoint() *PointMsg {
	if m != nil {
		return m.Point
	}
	return nil
}

func (m *PathNodeMsg) GetD() int32 {
	if m != nil {
		return m.D
	}
	return 0
}

func (m *PathNodeMsg) GetTrioId() int32 {
	if m != nil {
		return m.TrioId
	}
	return 0
}

func (m *PathNodeMsg) GetConnectionMask() uint32 {
	if m != nil {
		return m.ConnectionMask
	}
	return 0
}

func (m *PathNodeMsg) GetLinkedPathNodeIds() []int64 {
	if m != nil {
		return m.LinkedPathNodeIds
	}
	return nil
}

type PathContextResponseMsg struct {
	PathCtxId            int32        `protobuf:"varint,1,opt,name=path_ctx_id,json=pathCtxId,proto3" json:"path_ctx_id,omitempty"`
	GrowthContextId      int32        `protobuf:"varint,2,opt,name=growth_context_id,json=growthContextId,proto3" json:"growth_context_id,omitempty"`
	GrowthOffset         int32        `protobuf:"varint,3,opt,name=growth_offset,json=growthOffset,proto3" json:"growth_offset,omitempty"`
	RootPathNode         *PathNodeMsg `protobuf:"bytes,4,opt,name=root_path_node,json=rootPathNode,proto3" json:"root_path_node,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PathContextResponseMsg) Reset()         { *m = PathContextResponseMsg{} }
func (m *PathContextResponseMsg) String() string { return proto.CompactTextString(m) }
func (*PathContextResponseMsg) ProtoMessage()    {}
func (*PathContextResponseMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8f5151eb02dd926, []int{2}
}

func (m *PathContextResponseMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PathContextResponseMsg.Unmarshal(m, b)
}
func (m *PathContextResponseMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PathContextResponseMsg.Marshal(b, m, deterministic)
}
func (m *PathContextResponseMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PathContextResponseMsg.Merge(m, src)
}
func (m *PathContextResponseMsg) XXX_Size() int {
	return xxx_messageInfo_PathContextResponseMsg.Size(m)
}
func (m *PathContextResponseMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PathContextResponseMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PathContextResponseMsg proto.InternalMessageInfo

func (m *PathContextResponseMsg) GetPathCtxId() int32 {
	if m != nil {
		return m.PathCtxId
	}
	return 0
}

func (m *PathContextResponseMsg) GetGrowthContextId() int32 {
	if m != nil {
		return m.GrowthContextId
	}
	return 0
}

func (m *PathContextResponseMsg) GetGrowthOffset() int32 {
	if m != nil {
		return m.GrowthOffset
	}
	return 0
}

func (m *PathContextResponseMsg) GetRootPathNode() *PathNodeMsg {
	if m != nil {
		return m.RootPathNode
	}
	return nil
}

type ModifiedPathNodeMsg struct {
	PathNodeId           int64    `protobuf:"varint,1,opt,name=path_node_id,json=pathNodeId,proto3" json:"path_node_id,omitempty"`
	ConnectionMask       uint32   `protobuf:"varint,4,opt,name=connection_mask,json=connectionMask,proto3" json:"connection_mask,omitempty"`
	LinkedPathNodeIds    []int64  `protobuf:"varint,5,rep,packed,name=linked_path_node_ids,json=linkedPathNodeIds,proto3" json:"linked_path_node_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifiedPathNodeMsg) Reset()         { *m = ModifiedPathNodeMsg{} }
func (m *ModifiedPathNodeMsg) String() string { return proto.CompactTextString(m) }
func (*ModifiedPathNodeMsg) ProtoMessage()    {}
func (*ModifiedPathNodeMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8f5151eb02dd926, []int{3}
}

func (m *ModifiedPathNodeMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifiedPathNodeMsg.Unmarshal(m, b)
}
func (m *ModifiedPathNodeMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifiedPathNodeMsg.Marshal(b, m, deterministic)
}
func (m *ModifiedPathNodeMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifiedPathNodeMsg.Merge(m, src)
}
func (m *ModifiedPathNodeMsg) XXX_Size() int {
	return xxx_messageInfo_ModifiedPathNodeMsg.Size(m)
}
func (m *ModifiedPathNodeMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifiedPathNodeMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ModifiedPathNodeMsg proto.InternalMessageInfo

func (m *ModifiedPathNodeMsg) GetPathNodeId() int64 {
	if m != nil {
		return m.PathNodeId
	}
	return 0
}

func (m *ModifiedPathNodeMsg) GetConnectionMask() uint32 {
	if m != nil {
		return m.ConnectionMask
	}
	return 0
}

func (m *ModifiedPathNodeMsg) GetLinkedPathNodeIds() []int64 {
	if m != nil {
		return m.LinkedPathNodeIds
	}
	return nil
}

type NextMoveRequestMsg struct {
	PathCtxId            int32    `protobuf:"varint,1,opt,name=path_ctx_id,json=pathCtxId,proto3" json:"path_ctx_id,omitempty"`
	CurrentDist          int32    `protobuf:"varint,2,opt,name=current_dist,json=currentDist,proto3" json:"current_dist,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NextMoveRequestMsg) Reset()         { *m = NextMoveRequestMsg{} }
func (m *NextMoveRequestMsg) String() string { return proto.CompactTextString(m) }
func (*NextMoveRequestMsg) ProtoMessage()    {}
func (*NextMoveRequestMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8f5151eb02dd926, []int{4}
}

func (m *NextMoveRequestMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NextMoveRequestMsg.Unmarshal(m, b)
}
func (m *NextMoveRequestMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NextMoveRequestMsg.Marshal(b, m, deterministic)
}
func (m *NextMoveRequestMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NextMoveRequestMsg.Merge(m, src)
}
func (m *NextMoveRequestMsg) XXX_Size() int {
	return xxx_messageInfo_NextMoveRequestMsg.Size(m)
}
func (m *NextMoveRequestMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_NextMoveRequestMsg.DiscardUnknown(m)
}

var xxx_messageInfo_NextMoveRequestMsg proto.InternalMessageInfo

func (m *NextMoveRequestMsg) GetPathCtxId() int32 {
	if m != nil {
		return m.PathCtxId
	}
	return 0
}

func (m *NextMoveRequestMsg) GetCurrentDist() int32 {
	if m != nil {
		return m.CurrentDist
	}
	return 0
}

type NextMoveResponseMsg struct {
	PathCtxId            int32                  `protobuf:"varint,1,opt,name=path_ctx_id,json=pathCtxId,proto3" json:"path_ctx_id,omitempty"`
	NextDist             int32                  `protobuf:"varint,2,opt,name=next_dist,json=nextDist,proto3" json:"next_dist,omitempty"`
	ModifiedPathNodes    []*ModifiedPathNodeMsg `protobuf:"bytes,3,rep,name=modified_path_nodes,json=modifiedPathNodes,proto3" json:"modified_path_nodes,omitempty"`
	NewPathNodes         []*PathNodeMsg         `protobuf:"bytes,4,rep,name=new_path_nodes,json=newPathNodes,proto3" json:"new_path_nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *NextMoveResponseMsg) Reset()         { *m = NextMoveResponseMsg{} }
func (m *NextMoveResponseMsg) String() string { return proto.CompactTextString(m) }
func (*NextMoveResponseMsg) ProtoMessage()    {}
func (*NextMoveResponseMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8f5151eb02dd926, []int{5}
}

func (m *NextMoveResponseMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NextMoveResponseMsg.Unmarshal(m, b)
}
func (m *NextMoveResponseMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NextMoveResponseMsg.Marshal(b, m, deterministic)
}
func (m *NextMoveResponseMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NextMoveResponseMsg.Merge(m, src)
}
func (m *NextMoveResponseMsg) XXX_Size() int {
	return xxx_messageInfo_NextMoveResponseMsg.Size(m)
}
func (m *NextMoveResponseMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_NextMoveResponseMsg.DiscardUnknown(m)
}

var xxx_messageInfo_NextMoveResponseMsg proto.InternalMessageInfo

func (m *NextMoveResponseMsg) GetPathCtxId() int32 {
	if m != nil {
		return m.PathCtxId
	}
	return 0
}

func (m *NextMoveResponseMsg) GetNextDist() int32 {
	if m != nil {
		return m.NextDist
	}
	return 0
}

func (m *NextMoveResponseMsg) GetModifiedPathNodes() []*ModifiedPathNodeMsg {
	if m != nil {
		return m.ModifiedPathNodes
	}
	return nil
}

func (m *NextMoveResponseMsg) GetNewPathNodes() []*PathNodeMsg {
	if m != nil {
		return m.NewPathNodes
	}
	return nil
}

func init() {
	proto.RegisterType((*PathContextRequestMsg)(nil), "m3api.PathContextRequestMsg")
	proto.RegisterType((*PathNodeMsg)(nil), "m3api.PathNodeMsg")
	proto.RegisterType((*PathContextResponseMsg)(nil), "m3api.PathContextResponseMsg")
	proto.RegisterType((*ModifiedPathNodeMsg)(nil), "m3api.ModifiedPathNodeMsg")
	proto.RegisterType((*NextMoveRequestMsg)(nil), "m3api.NextMoveRequestMsg")
	proto.RegisterType((*NextMoveResponseMsg)(nil), "m3api.NextMoveResponseMsg")
}

func init() {
	proto.RegisterFile("m3path.proto", fileDescriptor_e8f5151eb02dd926)
}

var fileDescriptor_e8f5151eb02dd926 = []byte{
	// 485 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x95, 0x49, 0x53, 0xd8, 0x49, 0xba, 0x55, 0x5d, 0x3e, 0xa2, 0x45, 0x82, 0x6c, 0x10, 0xa2,
	0xe2, 0x50, 0xa4, 0xf6, 0xc2, 0x7d, 0xb9, 0x04, 0x29, 0x4b, 0x15, 0x21, 0x71, 0x8c, 0x42, 0xec,
	0xb6, 0x56, 0x89, 0x1d, 0x62, 0x2f, 0xcd, 0xde, 0xf8, 0x0b, 0xfc, 0x26, 0x7e, 0x04, 0xfc, 0x1c,
	0x64, 0xc7, 0x6d, 0x0a, 0x2a, 0xa2, 0x1c, 0xf3, 0xe6, 0xcd, 0x9b, 0x99, 0xf7, 0x1c, 0xf0, 0xcb,
	0x79, 0x95, 0xab, 0xf5, 0xb4, 0xaa, 0x85, 0x12, 0xd8, 0x2d, 0xe7, 0x79, 0xc5, 0x2e, 0x06, 0xe5,
	0xbc, 0x12, 0x8c, 0xab, 0x16, 0x8d, 0xbe, 0x22, 0x78, 0xb0, 0xc8, 0xd5, 0xfa, 0x4a, 0x70, 0x45,
	0x1b, 0x95, 0xd2, 0xcf, 0x37, 0x54, 0xaa, 0x44, 0xae, 0xf0, 0x53, 0xf0, 0x56, 0xb5, 0xd8, 0xaa,
	0x75, 0xa6, 0x6e, 0x2b, 0x1a, 0xa0, 0x10, 0x4d, 0xdc, 0x14, 0x5a, 0xe8, 0xfd, 0x6d, 0x45, 0xf1,
	0x25, 0xf8, 0x96, 0xc0, 0x38, 0xa1, 0x4d, 0x70, 0xc7, 0x30, 0x6c, 0x53, 0xac, 0x21, 0xfc, 0x0c,
	0x06, 0x96, 0x22, 0x96, 0x4b, 0x49, 0x55, 0xe0, 0x18, 0x8e, 0xed, 0x7b, 0x67, 0xb0, 0xe8, 0x07,
	0x02, 0x4f, 0xaf, 0x70, 0x2d, 0x08, 0xd5, 0x83, 0x43, 0xf0, 0xf5, 0xda, 0x19, 0x17, 0x84, 0x66,
	0x8c, 0x98, 0xc9, 0x4e, 0x0a, 0x95, 0xa5, 0xc4, 0x04, 0x3f, 0x07, 0xd7, 0xdc, 0x60, 0x46, 0x7a,
	0xb3, 0xe1, 0xd4, 0x9c, 0x36, 0x5d, 0x68, 0x2c, 0x91, 0xab, 0xb4, 0xad, 0x62, 0x1f, 0x10, 0xb1,
	0x13, 0x11, 0xc1, 0x8f, 0xe0, 0xae, 0xaa, 0x99, 0xd0, 0x8a, 0x3d, 0x83, 0xf5, 0xf5, 0x67, 0x4c,
	0xf0, 0x0b, 0x18, 0x16, 0x82, 0x73, 0x5a, 0x28, 0x26, 0x78, 0x56, 0xe6, 0x72, 0x13, 0xb8, 0x21,
	0x9a, 0x0c, 0xd2, 0xf3, 0x0e, 0x4e, 0x72, 0xb9, 0xc1, 0xaf, 0xe0, 0xfe, 0x27, 0xc6, 0x37, 0x94,
	0x64, 0x87, 0xfb, 0xc9, 0xa0, 0x1f, 0x3a, 0x13, 0x27, 0x1d, 0xb5, 0xb5, 0xc5, 0x7e, 0x4d, 0x19,
	0x7d, 0x47, 0xf0, 0xf0, 0x37, 0x73, 0x65, 0x25, 0xb8, 0x34, 0x47, 0x3e, 0x01, 0xcf, 0x88, 0x14,
	0xaa, 0xd9, 0xdd, 0xe8, 0xa6, 0x67, 0x1a, 0xba, 0x52, 0x4d, 0x4c, 0xf0, 0x4b, 0x18, 0x59, 0xe7,
	0x8a, 0xb6, 0x59, 0xb3, 0x5a, 0x87, 0x87, 0x6d, 0xc1, 0x8a, 0xc6, 0xe4, 0x24, 0x97, 0xf1, 0x6b,
	0x38, 0xaf, 0x85, 0x50, 0xdd, 0xea, 0xc6, 0x05, 0x6f, 0x86, 0x77, 0xe6, 0x75, 0x09, 0xa4, 0xbe,
	0x66, 0xee, 0x80, 0xe8, 0x1b, 0x82, 0x71, 0x22, 0x08, 0x5b, 0xb2, 0xee, 0xba, 0xd3, 0x72, 0x3a,
	0xe2, 0x6c, 0xef, 0xbf, 0x9c, 0x75, 0xff, 0xe6, 0xec, 0x07, 0xc0, 0xd7, 0xb4, 0x51, 0x89, 0xf8,
	0x42, 0x0f, 0x9e, 0xec, 0xbf, 0x4c, 0xbd, 0x04, 0xbf, 0xb8, 0xa9, 0x6b, 0xca, 0x55, 0x46, 0x98,
	0x54, 0xbb, 0x17, 0x6b, 0xb1, 0x37, 0x4c, 0xaa, 0xe8, 0x27, 0x82, 0x71, 0xa7, 0x7c, 0x7a, 0x5e,
	0x8f, 0xe1, 0x8c, 0xeb, 0x94, 0x0e, 0x74, 0xef, 0x69, 0x40, 0x8b, 0xe2, 0xb7, 0x30, 0x2e, 0xad,
	0x81, 0xdd, 0x81, 0x32, 0x70, 0x42, 0x67, 0xe2, 0xcd, 0x2e, 0x6c, 0x00, 0x47, 0x2c, 0x4e, 0x47,
	0xe5, 0x1f, 0xa0, 0xd4, 0x39, 0x72, 0xba, 0x3d, 0x94, 0xe9, 0x19, 0x99, 0xa3, 0x39, 0x72, 0xba,
	0xdd, 0x77, 0x7e, 0xec, 0x9b, 0x3f, 0x7e, 0xfe, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x9f, 0x85, 0xb0,
	0x27, 0x17, 0x04, 0x00, 0x00,
}
