// Code generated by protoc-gen-go. DO NOT EDIT.
// source: m3space.proto

package m3api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SpaceMsg struct {
	SpaceId                 int32    `protobuf:"varint,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	SpaceName               string   `protobuf:"bytes,2,opt,name=space_name,json=spaceName,proto3" json:"space_name,omitempty"`
	ActivePathNodeThreshold int32    `protobuf:"varint,3,opt,name=active_path_node_threshold,json=activePathNodeThreshold,proto3" json:"active_path_node_threshold,omitempty"`
	MaxTriosPerPoint        int32    `protobuf:"varint,4,opt,name=max_trios_per_point,json=maxTriosPerPoint,proto3" json:"max_trios_per_point,omitempty"`
	MaxPathNodesPerPoint    int32    `protobuf:"varint,5,opt,name=max_path_nodes_per_point,json=maxPathNodesPerPoint,proto3" json:"max_path_nodes_per_point,omitempty"`
	MaxTime                 int32    `protobuf:"varint,6,opt,name=max_time,json=maxTime,proto3" json:"max_time,omitempty"`
	CurrentTime             int32    `protobuf:"varint,7,opt,name=current_time,json=currentTime,proto3" json:"current_time,omitempty"`
	MaxCoord                int32    `protobuf:"varint,8,opt,name=max_coord,json=maxCoord,proto3" json:"max_coord,omitempty"`
	EventIds                []int32  `protobuf:"varint,9,rep,packed,name=event_ids,json=eventIds,proto3" json:"event_ids,omitempty"`
	NbActiveNodes           int32    `protobuf:"varint,10,opt,name=nb_active_nodes,json=nbActiveNodes,proto3" json:"nb_active_nodes,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *SpaceMsg) Reset()         { *m = SpaceMsg{} }
func (m *SpaceMsg) String() string { return proto.CompactTextString(m) }
func (*SpaceMsg) ProtoMessage()    {}
func (*SpaceMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c43524b64f4ebcab, []int{0}
}

func (m *SpaceMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpaceMsg.Unmarshal(m, b)
}
func (m *SpaceMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpaceMsg.Marshal(b, m, deterministic)
}
func (m *SpaceMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpaceMsg.Merge(m, src)
}
func (m *SpaceMsg) XXX_Size() int {
	return xxx_messageInfo_SpaceMsg.Size(m)
}
func (m *SpaceMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_SpaceMsg.DiscardUnknown(m)
}

var xxx_messageInfo_SpaceMsg proto.InternalMessageInfo

func (m *SpaceMsg) GetSpaceId() int32 {
	if m != nil {
		return m.SpaceId
	}
	return 0
}

func (m *SpaceMsg) GetSpaceName() string {
	if m != nil {
		return m.SpaceName
	}
	return ""
}

func (m *SpaceMsg) GetActivePathNodeThreshold() int32 {
	if m != nil {
		return m.ActivePathNodeThreshold
	}
	return 0
}

func (m *SpaceMsg) GetMaxTriosPerPoint() int32 {
	if m != nil {
		return m.MaxTriosPerPoint
	}
	return 0
}

func (m *SpaceMsg) GetMaxPathNodesPerPoint() int32 {
	if m != nil {
		return m.MaxPathNodesPerPoint
	}
	return 0
}

func (m *SpaceMsg) GetMaxTime() int32 {
	if m != nil {
		return m.MaxTime
	}
	return 0
}

func (m *SpaceMsg) GetCurrentTime() int32 {
	if m != nil {
		return m.CurrentTime
	}
	return 0
}

func (m *SpaceMsg) GetMaxCoord() int32 {
	if m != nil {
		return m.MaxCoord
	}
	return 0
}

func (m *SpaceMsg) GetEventIds() []int32 {
	if m != nil {
		return m.EventIds
	}
	return nil
}

func (m *SpaceMsg) GetNbActiveNodes() int32 {
	if m != nil {
		return m.NbActiveNodes
	}
	return 0
}

type SpaceListMsg struct {
	Spaces               []*SpaceMsg `protobuf:"bytes,1,rep,name=spaces,proto3" json:"spaces,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SpaceListMsg) Reset()         { *m = SpaceListMsg{} }
func (m *SpaceListMsg) String() string { return proto.CompactTextString(m) }
func (*SpaceListMsg) ProtoMessage()    {}
func (*SpaceListMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c43524b64f4ebcab, []int{1}
}

func (m *SpaceListMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpaceListMsg.Unmarshal(m, b)
}
func (m *SpaceListMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpaceListMsg.Marshal(b, m, deterministic)
}
func (m *SpaceListMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpaceListMsg.Merge(m, src)
}
func (m *SpaceListMsg) XXX_Size() int {
	return xxx_messageInfo_SpaceListMsg.Size(m)
}
func (m *SpaceListMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_SpaceListMsg.DiscardUnknown(m)
}

var xxx_messageInfo_SpaceListMsg proto.InternalMessageInfo

func (m *SpaceListMsg) GetSpaces() []*SpaceMsg {
	if m != nil {
		return m.Spaces
	}
	return nil
}

type EventMsg struct {
	EventId              int32     `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	SpaceId              int32     `protobuf:"varint,2,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	GrowthType           int32     `protobuf:"varint,3,opt,name=growth_type,json=growthType,proto3" json:"growth_type,omitempty"`
	GrowthIndex          int32     `protobuf:"varint,4,opt,name=growth_index,json=growthIndex,proto3" json:"growth_index,omitempty"`
	GrowthOffset         int32     `protobuf:"varint,5,opt,name=growth_offset,json=growthOffset,proto3" json:"growth_offset,omitempty"`
	CreationTime         int32     `protobuf:"varint,6,opt,name=creation_time,json=creationTime,proto3" json:"creation_time,omitempty"`
	Center               *PointMsg `protobuf:"bytes,7,opt,name=center,proto3" json:"center,omitempty"`
	Color                uint32    `protobuf:"varint,8,opt,name=color,proto3" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EventMsg) Reset()         { *m = EventMsg{} }
func (m *EventMsg) String() string { return proto.CompactTextString(m) }
func (*EventMsg) ProtoMessage()    {}
func (*EventMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c43524b64f4ebcab, []int{2}
}

func (m *EventMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventMsg.Unmarshal(m, b)
}
func (m *EventMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventMsg.Marshal(b, m, deterministic)
}
func (m *EventMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventMsg.Merge(m, src)
}
func (m *EventMsg) XXX_Size() int {
	return xxx_messageInfo_EventMsg.Size(m)
}
func (m *EventMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_EventMsg.DiscardUnknown(m)
}

var xxx_messageInfo_EventMsg proto.InternalMessageInfo

func (m *EventMsg) GetEventId() int32 {
	if m != nil {
		return m.EventId
	}
	return 0
}

func (m *EventMsg) GetSpaceId() int32 {
	if m != nil {
		return m.SpaceId
	}
	return 0
}

func (m *EventMsg) GetGrowthType() int32 {
	if m != nil {
		return m.GrowthType
	}
	return 0
}

func (m *EventMsg) GetGrowthIndex() int32 {
	if m != nil {
		return m.GrowthIndex
	}
	return 0
}

func (m *EventMsg) GetGrowthOffset() int32 {
	if m != nil {
		return m.GrowthOffset
	}
	return 0
}

func (m *EventMsg) GetCreationTime() int32 {
	if m != nil {
		return m.CreationTime
	}
	return 0
}

func (m *EventMsg) GetCenter() *PointMsg {
	if m != nil {
		return m.Center
	}
	return nil
}

func (m *EventMsg) GetColor() uint32 {
	if m != nil {
		return m.Color
	}
	return 0
}

type NodeEventMsg struct {
	EventId              int32     `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Point                *PointMsg `protobuf:"bytes,2,opt,name=point,proto3" json:"point,omitempty"`
	D                    int32     `protobuf:"varint,3,opt,name=d,proto3" json:"d,omitempty"`
	TrioId               int32     `protobuf:"varint,4,opt,name=trio_id,json=trioId,proto3" json:"trio_id,omitempty"`
	ConnectionMask       uint32    `protobuf:"varint,5,opt,name=connection_mask,json=connectionMask,proto3" json:"connection_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *NodeEventMsg) Reset()         { *m = NodeEventMsg{} }
func (m *NodeEventMsg) String() string { return proto.CompactTextString(m) }
func (*NodeEventMsg) ProtoMessage()    {}
func (*NodeEventMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c43524b64f4ebcab, []int{3}
}

func (m *NodeEventMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeEventMsg.Unmarshal(m, b)
}
func (m *NodeEventMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeEventMsg.Marshal(b, m, deterministic)
}
func (m *NodeEventMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeEventMsg.Merge(m, src)
}
func (m *NodeEventMsg) XXX_Size() int {
	return xxx_messageInfo_NodeEventMsg.Size(m)
}
func (m *NodeEventMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeEventMsg.DiscardUnknown(m)
}

var xxx_messageInfo_NodeEventMsg proto.InternalMessageInfo

func (m *NodeEventMsg) GetEventId() int32 {
	if m != nil {
		return m.EventId
	}
	return 0
}

func (m *NodeEventMsg) GetPoint() *PointMsg {
	if m != nil {
		return m.Point
	}
	return nil
}

func (m *NodeEventMsg) GetD() int32 {
	if m != nil {
		return m.D
	}
	return 0
}

func (m *NodeEventMsg) GetTrioId() int32 {
	if m != nil {
		return m.TrioId
	}
	return 0
}

func (m *NodeEventMsg) GetConnectionMask() uint32 {
	if m != nil {
		return m.ConnectionMask
	}
	return 0
}

type EventResponseMsg struct {
	EventId              int32         `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	PathCtxId            int64         `protobuf:"varint,2,opt,name=path_ctx_id,json=pathCtxId,proto3" json:"path_ctx_id,omitempty"`
	RootNode             *NodeEventMsg `protobuf:"bytes,3,opt,name=root_node,json=rootNode,proto3" json:"root_node,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *EventResponseMsg) Reset()         { *m = EventResponseMsg{} }
func (m *EventResponseMsg) String() string { return proto.CompactTextString(m) }
func (*EventResponseMsg) ProtoMessage()    {}
func (*EventResponseMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c43524b64f4ebcab, []int{4}
}

func (m *EventResponseMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventResponseMsg.Unmarshal(m, b)
}
func (m *EventResponseMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventResponseMsg.Marshal(b, m, deterministic)
}
func (m *EventResponseMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventResponseMsg.Merge(m, src)
}
func (m *EventResponseMsg) XXX_Size() int {
	return xxx_messageInfo_EventResponseMsg.Size(m)
}
func (m *EventResponseMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_EventResponseMsg.DiscardUnknown(m)
}

var xxx_messageInfo_EventResponseMsg proto.InternalMessageInfo

func (m *EventResponseMsg) GetEventId() int32 {
	if m != nil {
		return m.EventId
	}
	return 0
}

func (m *EventResponseMsg) GetPathCtxId() int64 {
	if m != nil {
		return m.PathCtxId
	}
	return 0
}

func (m *EventResponseMsg) GetRootNode() *NodeEventMsg {
	if m != nil {
		return m.RootNode
	}
	return nil
}

type SpaceTimeRequestMsg struct {
	SpaceId              int32    `protobuf:"varint,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	CurrentTime          int32    `protobuf:"varint,2,opt,name=current_time,json=currentTime,proto3" json:"current_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpaceTimeRequestMsg) Reset()         { *m = SpaceTimeRequestMsg{} }
func (m *SpaceTimeRequestMsg) String() string { return proto.CompactTextString(m) }
func (*SpaceTimeRequestMsg) ProtoMessage()    {}
func (*SpaceTimeRequestMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c43524b64f4ebcab, []int{5}
}

func (m *SpaceTimeRequestMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpaceTimeRequestMsg.Unmarshal(m, b)
}
func (m *SpaceTimeRequestMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpaceTimeRequestMsg.Marshal(b, m, deterministic)
}
func (m *SpaceTimeRequestMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpaceTimeRequestMsg.Merge(m, src)
}
func (m *SpaceTimeRequestMsg) XXX_Size() int {
	return xxx_messageInfo_SpaceTimeRequestMsg.Size(m)
}
func (m *SpaceTimeRequestMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_SpaceTimeRequestMsg.DiscardUnknown(m)
}

var xxx_messageInfo_SpaceTimeRequestMsg proto.InternalMessageInfo

func (m *SpaceTimeRequestMsg) GetSpaceId() int32 {
	if m != nil {
		return m.SpaceId
	}
	return 0
}

func (m *SpaceTimeRequestMsg) GetCurrentTime() int32 {
	if m != nil {
		return m.CurrentTime
	}
	return 0
}

type SpaceTimeResponseMsg struct {
	SpaceId              int32           `protobuf:"varint,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	CurrentTime          int32           `protobuf:"varint,2,opt,name=current_time,json=currentTime,proto3" json:"current_time,omitempty"`
	ActiveNodes          []*NodeEventMsg `protobuf:"bytes,3,rep,name=active_nodes,json=activeNodes,proto3" json:"active_nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SpaceTimeResponseMsg) Reset()         { *m = SpaceTimeResponseMsg{} }
func (m *SpaceTimeResponseMsg) String() string { return proto.CompactTextString(m) }
func (*SpaceTimeResponseMsg) ProtoMessage()    {}
func (*SpaceTimeResponseMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c43524b64f4ebcab, []int{6}
}

func (m *SpaceTimeResponseMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpaceTimeResponseMsg.Unmarshal(m, b)
}
func (m *SpaceTimeResponseMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpaceTimeResponseMsg.Marshal(b, m, deterministic)
}
func (m *SpaceTimeResponseMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpaceTimeResponseMsg.Merge(m, src)
}
func (m *SpaceTimeResponseMsg) XXX_Size() int {
	return xxx_messageInfo_SpaceTimeResponseMsg.Size(m)
}
func (m *SpaceTimeResponseMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_SpaceTimeResponseMsg.DiscardUnknown(m)
}

var xxx_messageInfo_SpaceTimeResponseMsg proto.InternalMessageInfo

func (m *SpaceTimeResponseMsg) GetSpaceId() int32 {
	if m != nil {
		return m.SpaceId
	}
	return 0
}

func (m *SpaceTimeResponseMsg) GetCurrentTime() int32 {
	if m != nil {
		return m.CurrentTime
	}
	return 0
}

func (m *SpaceTimeResponseMsg) GetActiveNodes() []*NodeEventMsg {
	if m != nil {
		return m.ActiveNodes
	}
	return nil
}

func init() {
	proto.RegisterType((*SpaceMsg)(nil), "m3api.SpaceMsg")
	proto.RegisterType((*SpaceListMsg)(nil), "m3api.SpaceListMsg")
	proto.RegisterType((*EventMsg)(nil), "m3api.EventMsg")
	proto.RegisterType((*NodeEventMsg)(nil), "m3api.NodeEventMsg")
	proto.RegisterType((*EventResponseMsg)(nil), "m3api.EventResponseMsg")
	proto.RegisterType((*SpaceTimeRequestMsg)(nil), "m3api.SpaceTimeRequestMsg")
	proto.RegisterType((*SpaceTimeResponseMsg)(nil), "m3api.SpaceTimeResponseMsg")
}

func init() {
	proto.RegisterFile("m3space.proto", fileDescriptor_c43524b64f4ebcab)
}

var fileDescriptor_c43524b64f4ebcab = []byte{
	// 615 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x41, 0x4f, 0x14, 0x4d,
	0x10, 0xcd, 0xec, 0x7e, 0xbb, 0xec, 0xd6, 0xce, 0x7c, 0x90, 0x86, 0x84, 0x01, 0xa3, 0xae, 0x63,
	0x14, 0x2e, 0x12, 0xc3, 0x26, 0x78, 0xf0, 0x64, 0x88, 0x87, 0x4d, 0x04, 0xc9, 0xc0, 0x7d, 0xd2,
	0x4c, 0x17, 0xec, 0x04, 0xa6, 0x7b, 0xec, 0x6e, 0x70, 0x38, 0x79, 0xf5, 0xa0, 0xff, 0xc1, 0x9f,
	0x6a, 0xba, 0xa6, 0xc7, 0xdd, 0x55, 0x12, 0x8c, 0xc7, 0x7e, 0xaf, 0xaa, 0xba, 0xea, 0xbd, 0xea,
	0x86, 0xa8, 0x9c, 0x98, 0x8a, 0xe7, 0xb8, 0x57, 0x69, 0x65, 0x15, 0xeb, 0x95, 0x13, 0x5e, 0x15,
	0xdb, 0x51, 0x39, 0xa9, 0x54, 0x21, 0x6d, 0x83, 0x26, 0x5f, 0xbb, 0x30, 0x38, 0x75, 0x51, 0x47,
	0xe6, 0x92, 0x6d, 0xc1, 0x80, 0x32, 0xb2, 0x42, 0xc4, 0xc1, 0x38, 0xd8, 0xed, 0xa5, 0x2b, 0x74,
	0x9e, 0x0a, 0xf6, 0x18, 0xa0, 0xa1, 0x24, 0x2f, 0x31, 0xee, 0x8c, 0x83, 0xdd, 0x61, 0x3a, 0x24,
	0xe4, 0x98, 0x97, 0xc8, 0xde, 0xc2, 0x36, 0xcf, 0x6d, 0x71, 0x8b, 0x59, 0xc5, 0xed, 0x2c, 0x93,
	0x4a, 0x60, 0x66, 0x67, 0x1a, 0xcd, 0x4c, 0x5d, 0x8b, 0xb8, 0x4b, 0xb5, 0x36, 0x9b, 0x88, 0x13,
	0x6e, 0x67, 0xc7, 0x4a, 0xe0, 0x59, 0x4b, 0xb3, 0x57, 0xb0, 0x5e, 0xf2, 0x3a, 0xb3, 0xba, 0x50,
	0x26, 0xab, 0x50, 0x67, 0xd4, 0x60, 0xfc, 0x1f, 0x65, 0xad, 0x95, 0xbc, 0x3e, 0x73, 0xcc, 0x09,
	0xea, 0x13, 0x87, 0xb3, 0x03, 0x88, 0x5d, 0xf8, 0xaf, 0x8b, 0x16, 0x73, 0x7a, 0x94, 0xb3, 0x51,
	0xf2, 0xba, 0xbd, 0x66, 0x9e, 0xb7, 0x05, 0x03, 0xba, 0xa6, 0x28, 0x31, 0xee, 0x37, 0xd3, 0xb9,
	0xda, 0x45, 0x89, 0xec, 0x19, 0x84, 0xf9, 0x8d, 0xd6, 0x28, 0x6d, 0x43, 0xaf, 0x10, 0x3d, 0xf2,
	0x18, 0x85, 0x3c, 0x82, 0xa1, 0xcb, 0xce, 0x95, 0xd2, 0x22, 0x1e, 0x10, 0xef, 0xca, 0x1d, 0xba,
	0xb3, 0x23, 0xf1, 0xd6, 0x65, 0x17, 0xc2, 0xc4, 0xc3, 0x71, 0xd7, 0x91, 0x04, 0x4c, 0x85, 0x61,
	0x2f, 0x61, 0x55, 0x9e, 0x67, 0x5e, 0x1e, 0x6a, 0x38, 0x06, 0xca, 0x8f, 0xe4, 0xf9, 0x3b, 0x42,
	0xa9, 0xcf, 0xe4, 0x0d, 0x84, 0xe4, 0xc4, 0x87, 0xc2, 0x58, 0xe7, 0xc6, 0x0e, 0xf4, 0x49, 0x60,
	0x13, 0x07, 0xe3, 0xee, 0xee, 0x68, 0x7f, 0x75, 0x8f, 0x1c, 0xdc, 0x6b, 0xed, 0x4a, 0x3d, 0x9d,
	0x7c, 0xef, 0xc0, 0xe0, 0xbd, 0xbb, 0xcd, 0x7b, 0xd8, 0xb6, 0xd2, 0x7a, 0xe8, 0x3b, 0x59, 0xb2,
	0xb7, 0xb3, 0x6c, 0xef, 0x53, 0x18, 0x5d, 0x6a, 0xf5, 0xd9, 0xce, 0x32, 0x7b, 0x57, 0xa1, 0x37,
	0x0c, 0x1a, 0xe8, 0xec, 0xae, 0x22, 0x85, 0x7c, 0x40, 0x21, 0x05, 0xd6, 0xde, 0x1c, 0x9f, 0x34,
	0x75, 0x10, 0x7b, 0x0e, 0x91, 0x0f, 0x51, 0x17, 0x17, 0x06, 0x5b, 0x33, 0x7c, 0xde, 0x47, 0xc2,
	0x5c, 0x50, 0xae, 0x91, 0xdb, 0x42, 0xc9, 0x45, 0x27, 0xc2, 0x16, 0x24, 0xad, 0x77, 0xa0, 0x9f,
	0xa3, 0xb4, 0xa8, 0xc9, 0x88, 0xf9, 0xe4, 0xe4, 0x23, 0x4d, 0xde, 0xd0, 0x6c, 0x03, 0x7a, 0xb9,
	0xba, 0x56, 0x9a, 0x0c, 0x89, 0xd2, 0xe6, 0x90, 0xfc, 0x08, 0x20, 0x74, 0x92, 0xfe, 0x8d, 0x26,
	0x2f, 0xa0, 0xd7, 0x6c, 0x4e, 0xe7, 0xfe, 0x9b, 0x1a, 0x96, 0x85, 0x10, 0xb4, 0x6b, 0x1c, 0x08,
	0xb6, 0x09, 0x2b, 0x6e, 0x59, 0x5d, 0xb9, 0x46, 0x87, 0xbe, 0x3b, 0x4e, 0x05, 0xdb, 0x81, 0xd5,
	0x5c, 0x49, 0x89, 0x39, 0xcd, 0x57, 0x72, 0x73, 0x45, 0x22, 0x44, 0xe9, 0xff, 0x73, 0xf8, 0x88,
	0x9b, 0xab, 0xe4, 0x0b, 0xac, 0x51, 0x77, 0x29, 0x9a, 0x4a, 0x49, 0x83, 0x0f, 0x74, 0xf9, 0x04,
	0x46, 0xb4, 0xee, 0xb9, 0xad, 0x5b, 0xf3, 0xba, 0xe9, 0xd0, 0x41, 0x87, 0xb6, 0x9e, 0x0a, 0xf6,
	0x1a, 0x86, 0x5a, 0x29, 0x4b, 0xdb, 0x45, 0x6d, 0x8e, 0xf6, 0xd7, 0xfd, 0x24, 0x8b, 0x42, 0xa4,
	0x03, 0x17, 0xe5, 0x90, 0xe4, 0x14, 0xd6, 0x69, 0x8f, 0x9c, 0xde, 0x29, 0x7e, 0xba, 0x41, 0x63,
	0x1f, 0xf8, 0x01, 0x7e, 0x7f, 0x23, 0x9d, 0x3f, 0xde, 0x48, 0xf2, 0x2d, 0x80, 0x8d, 0x85, 0xaa,
	0x4b, 0xa3, 0xfd, 0x7b, 0x59, 0x76, 0x00, 0xe1, 0xd2, 0xeb, 0xe9, 0xd2, 0x73, 0xb8, 0x77, 0xc0,
	0x11, 0x9f, 0x3f, 0xa8, 0xf3, 0x3e, 0x7d, 0x71, 0x93, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x27,
	0x41, 0x3d, 0x79, 0x09, 0x05, 0x00, 0x00,
}
