// Code generated by protoc-gen-go. DO NOT EDIT.
// source: m3space.proto

package m3api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SpaceMsg struct {
	SpaceId              int32    `protobuf:"varint,1,opt,name=space_id,json=spaceId,proto3" json:"space_id" query:"space_id"`
	SpaceName            string   `protobuf:"bytes,2,opt,name=space_name,json=spaceName,proto3" json:"space_name" query:"space_name"`
	ActiveThreshold      int32    `protobuf:"varint,3,opt,name=active_threshold,json=activeThreshold,proto3" json:"active_threshold" query:"active_threshold"`
	MaxTriosPerPoint     int32    `protobuf:"varint,4,opt,name=max_trios_per_point,json=maxTriosPerPoint,proto3" json:"max_trios_per_point" query:"max_trios_per_point"`
	MaxNodesPerPoint     int32    `protobuf:"varint,5,opt,name=max_nodes_per_point,json=maxNodesPerPoint,proto3" json:"max_nodes_per_point" query:"max_nodes_per_point"`
	MaxTime              int32    `protobuf:"varint,6,opt,name=max_time,json=maxTime,proto3" json:"max_time" query:"max_time"`
	MaxCoord             int32    `protobuf:"varint,8,opt,name=max_coord,json=maxCoord,proto3" json:"max_coord" query:"max_coord"`
	EventIds             []int32  `protobuf:"varint,9,rep,packed,name=event_ids,json=eventIds,proto3" json:"event_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" query:"-"`
	XXX_unrecognized     []byte   `json:"-" query:"-"`
	XXX_sizecache        int32    `json:"-" query:"-"`
}

func (m *SpaceMsg) Reset()         { *m = SpaceMsg{} }
func (m *SpaceMsg) String() string { return proto.CompactTextString(m) }
func (*SpaceMsg) ProtoMessage()    {}
func (*SpaceMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c43524b64f4ebcab, []int{0}
}

func (m *SpaceMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpaceMsg.Unmarshal(m, b)
}
func (m *SpaceMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpaceMsg.Marshal(b, m, deterministic)
}
func (m *SpaceMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpaceMsg.Merge(m, src)
}
func (m *SpaceMsg) XXX_Size() int {
	return xxx_messageInfo_SpaceMsg.Size(m)
}
func (m *SpaceMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_SpaceMsg.DiscardUnknown(m)
}

var xxx_messageInfo_SpaceMsg proto.InternalMessageInfo

func (m *SpaceMsg) GetSpaceId() int32 {
	if m != nil {
		return m.SpaceId
	}
	return 0
}

func (m *SpaceMsg) GetSpaceName() string {
	if m != nil {
		return m.SpaceName
	}
	return ""
}

func (m *SpaceMsg) GetActiveThreshold() int32 {
	if m != nil {
		return m.ActiveThreshold
	}
	return 0
}

func (m *SpaceMsg) GetMaxTriosPerPoint() int32 {
	if m != nil {
		return m.MaxTriosPerPoint
	}
	return 0
}

func (m *SpaceMsg) GetMaxNodesPerPoint() int32 {
	if m != nil {
		return m.MaxNodesPerPoint
	}
	return 0
}

func (m *SpaceMsg) GetMaxTime() int32 {
	if m != nil {
		return m.MaxTime
	}
	return 0
}

func (m *SpaceMsg) GetMaxCoord() int32 {
	if m != nil {
		return m.MaxCoord
	}
	return 0
}

func (m *SpaceMsg) GetEventIds() []int32 {
	if m != nil {
		return m.EventIds
	}
	return nil
}

type SpaceListMsg struct {
	Spaces               []*SpaceMsg `protobuf:"bytes,1,rep,name=spaces,proto3" json:"spaces,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-" query:"-"`
	XXX_unrecognized     []byte      `json:"-" query:"-"`
	XXX_sizecache        int32       `json:"-" query:"-"`
}

func (m *SpaceListMsg) Reset()         { *m = SpaceListMsg{} }
func (m *SpaceListMsg) String() string { return proto.CompactTextString(m) }
func (*SpaceListMsg) ProtoMessage()    {}
func (*SpaceListMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c43524b64f4ebcab, []int{1}
}

func (m *SpaceListMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpaceListMsg.Unmarshal(m, b)
}
func (m *SpaceListMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpaceListMsg.Marshal(b, m, deterministic)
}
func (m *SpaceListMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpaceListMsg.Merge(m, src)
}
func (m *SpaceListMsg) XXX_Size() int {
	return xxx_messageInfo_SpaceListMsg.Size(m)
}
func (m *SpaceListMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_SpaceListMsg.DiscardUnknown(m)
}

var xxx_messageInfo_SpaceListMsg proto.InternalMessageInfo

func (m *SpaceListMsg) GetSpaces() []*SpaceMsg {
	if m != nil {
		return m.Spaces
	}
	return nil
}

type EventRequestMsg struct {
	SpaceId              int32     `protobuf:"varint,2,opt,name=space_id,json=spaceId,proto3" json:"space_id" query:"space_id"`
	GrowthType           int32     `protobuf:"varint,3,opt,name=growth_type,json=growthType,proto3" json:"growth_type" query:"growth_type"`
	GrowthIndex          int32     `protobuf:"varint,4,opt,name=growth_index,json=growthIndex,proto3" json:"growth_index" query:"growth_index"`
	GrowthOffset         int32     `protobuf:"varint,5,opt,name=growth_offset,json=growthOffset,proto3" json:"growth_offset" query:"growth_offset"`
	CreationTime         int32     `protobuf:"varint,6,opt,name=creation_time,json=creationTime,proto3" json:"creation_time" query:"creation_time"`
	Center               *PointMsg `protobuf:"bytes,7,opt,name=center,proto3" json:"center,omitempty"`
	Color                uint32    `protobuf:"varint,8,opt,name=color,proto3" json:"color" query:"color"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-" query:"-"`
	XXX_unrecognized     []byte    `json:"-" query:"-"`
	XXX_sizecache        int32     `json:"-" query:"-"`
}

func (m *EventRequestMsg) Reset()         { *m = EventRequestMsg{} }
func (m *EventRequestMsg) String() string { return proto.CompactTextString(m) }
func (*EventRequestMsg) ProtoMessage()    {}
func (*EventRequestMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c43524b64f4ebcab, []int{2}
}

func (m *EventRequestMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventRequestMsg.Unmarshal(m, b)
}
func (m *EventRequestMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventRequestMsg.Marshal(b, m, deterministic)
}
func (m *EventRequestMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventRequestMsg.Merge(m, src)
}
func (m *EventRequestMsg) XXX_Size() int {
	return xxx_messageInfo_EventRequestMsg.Size(m)
}
func (m *EventRequestMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_EventRequestMsg.DiscardUnknown(m)
}

var xxx_messageInfo_EventRequestMsg proto.InternalMessageInfo

func (m *EventRequestMsg) GetSpaceId() int32 {
	if m != nil {
		return m.SpaceId
	}
	return 0
}

func (m *EventRequestMsg) GetGrowthType() int32 {
	if m != nil {
		return m.GrowthType
	}
	return 0
}

func (m *EventRequestMsg) GetGrowthIndex() int32 {
	if m != nil {
		return m.GrowthIndex
	}
	return 0
}

func (m *EventRequestMsg) GetGrowthOffset() int32 {
	if m != nil {
		return m.GrowthOffset
	}
	return 0
}

func (m *EventRequestMsg) GetCreationTime() int32 {
	if m != nil {
		return m.CreationTime
	}
	return 0
}

func (m *EventRequestMsg) GetCenter() *PointMsg {
	if m != nil {
		return m.Center
	}
	return nil
}

func (m *EventRequestMsg) GetColor() uint32 {
	if m != nil {
		return m.Color
	}
	return 0
}

type NodeEventMsg struct {
	EventNodeId          int64     `protobuf:"varint,1,opt,name=event_node_id,json=eventNodeId,proto3" json:"event_node_id" query:"event_node_id"`
	EventId              int32     `protobuf:"varint,2,opt,name=event_id,json=eventId,proto3" json:"event_id" query:"event_id"`
	Point                *PointMsg `protobuf:"bytes,3,opt,name=point,proto3" json:"point,omitempty"`
	CreationTime         int32     `protobuf:"varint,4,opt,name=creation_time,json=creationTime,proto3" json:"creation_time" query:"creation_time"`
	D                    int32     `protobuf:"varint,5,opt,name=d,proto3" json:"d" query:"d"`
	TrioId               int32     `protobuf:"varint,6,opt,name=trio_id,json=trioId,proto3" json:"trio_id" query:"trio_id"`
	ConnectionMask       uint32    `protobuf:"varint,7,opt,name=connection_mask,json=connectionMask,proto3" json:"connection_mask" query:"connection_mask"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-" query:"-"`
	XXX_unrecognized     []byte    `json:"-" query:"-"`
	XXX_sizecache        int32     `json:"-" query:"-"`
}

func (m *NodeEventMsg) Reset()         { *m = NodeEventMsg{} }
func (m *NodeEventMsg) String() string { return proto.CompactTextString(m) }
func (*NodeEventMsg) ProtoMessage()    {}
func (*NodeEventMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c43524b64f4ebcab, []int{3}
}

func (m *NodeEventMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeEventMsg.Unmarshal(m, b)
}
func (m *NodeEventMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeEventMsg.Marshal(b, m, deterministic)
}
func (m *NodeEventMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeEventMsg.Merge(m, src)
}
func (m *NodeEventMsg) XXX_Size() int {
	return xxx_messageInfo_NodeEventMsg.Size(m)
}
func (m *NodeEventMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeEventMsg.DiscardUnknown(m)
}

var xxx_messageInfo_NodeEventMsg proto.InternalMessageInfo

func (m *NodeEventMsg) GetEventNodeId() int64 {
	if m != nil {
		return m.EventNodeId
	}
	return 0
}

func (m *NodeEventMsg) GetEventId() int32 {
	if m != nil {
		return m.EventId
	}
	return 0
}

func (m *NodeEventMsg) GetPoint() *PointMsg {
	if m != nil {
		return m.Point
	}
	return nil
}

func (m *NodeEventMsg) GetCreationTime() int32 {
	if m != nil {
		return m.CreationTime
	}
	return 0
}

func (m *NodeEventMsg) GetD() int32 {
	if m != nil {
		return m.D
	}
	return 0
}

func (m *NodeEventMsg) GetTrioId() int32 {
	if m != nil {
		return m.TrioId
	}
	return 0
}

func (m *NodeEventMsg) GetConnectionMask() uint32 {
	if m != nil {
		return m.ConnectionMask
	}
	return 0
}

type EventMsg struct {
	EventId              int32         `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id" query:"event_id"`
	SpaceId              int32         `protobuf:"varint,2,opt,name=space_id,json=spaceId,proto3" json:"space_id" query:"space_id"`
	GrowthType           int32         `protobuf:"varint,3,opt,name=growth_type,json=growthType,proto3" json:"growth_type" query:"growth_type"`
	GrowthIndex          int32         `protobuf:"varint,4,opt,name=growth_index,json=growthIndex,proto3" json:"growth_index" query:"growth_index"`
	GrowthOffset         int32         `protobuf:"varint,5,opt,name=growth_offset,json=growthOffset,proto3" json:"growth_offset" query:"growth_offset"`
	CreationTime         int32         `protobuf:"varint,6,opt,name=creation_time,json=creationTime,proto3" json:"creation_time" query:"creation_time"`
	PathCtxId            int32         `protobuf:"varint,7,opt,name=path_ctx_id,json=pathCtxId,proto3" json:"path_ctx_id" query:"path_ctx_id"`
	Color                uint32        `protobuf:"varint,8,opt,name=color,proto3" json:"color" query:"color"`
	RootNode             *NodeEventMsg `protobuf:"bytes,9,opt,name=root_node,json=rootNode,proto3" json:"root_node,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-" query:"-"`
	XXX_unrecognized     []byte        `json:"-" query:"-"`
	XXX_sizecache        int32         `json:"-" query:"-"`
}

func (m *EventMsg) Reset()         { *m = EventMsg{} }
func (m *EventMsg) String() string { return proto.CompactTextString(m) }
func (*EventMsg) ProtoMessage()    {}
func (*EventMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c43524b64f4ebcab, []int{4}
}

func (m *EventMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventMsg.Unmarshal(m, b)
}
func (m *EventMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventMsg.Marshal(b, m, deterministic)
}
func (m *EventMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventMsg.Merge(m, src)
}
func (m *EventMsg) XXX_Size() int {
	return xxx_messageInfo_EventMsg.Size(m)
}
func (m *EventMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_EventMsg.DiscardUnknown(m)
}

var xxx_messageInfo_EventMsg proto.InternalMessageInfo

func (m *EventMsg) GetEventId() int32 {
	if m != nil {
		return m.EventId
	}
	return 0
}

func (m *EventMsg) GetSpaceId() int32 {
	if m != nil {
		return m.SpaceId
	}
	return 0
}

func (m *EventMsg) GetGrowthType() int32 {
	if m != nil {
		return m.GrowthType
	}
	return 0
}

func (m *EventMsg) GetGrowthIndex() int32 {
	if m != nil {
		return m.GrowthIndex
	}
	return 0
}

func (m *EventMsg) GetGrowthOffset() int32 {
	if m != nil {
		return m.GrowthOffset
	}
	return 0
}

func (m *EventMsg) GetCreationTime() int32 {
	if m != nil {
		return m.CreationTime
	}
	return 0
}

func (m *EventMsg) GetPathCtxId() int32 {
	if m != nil {
		return m.PathCtxId
	}
	return 0
}

func (m *EventMsg) GetColor() uint32 {
	if m != nil {
		return m.Color
	}
	return 0
}

func (m *EventMsg) GetRootNode() *NodeEventMsg {
	if m != nil {
		return m.RootNode
	}
	return nil
}

type SpaceTimeRequestMsg struct {
	SpaceId              int32    `protobuf:"varint,1,opt,name=space_id,json=spaceId,proto3" json:"space_id" query:"space_id"`
	CurrentTime          int32    `protobuf:"varint,2,opt,name=current_time,json=currentTime,proto3" json:"current_time" query:"current_time"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" query:"-"`
	XXX_unrecognized     []byte   `json:"-" query:"-"`
	XXX_sizecache        int32    `json:"-" query:"-"`
}

func (m *SpaceTimeRequestMsg) Reset()         { *m = SpaceTimeRequestMsg{} }
func (m *SpaceTimeRequestMsg) String() string { return proto.CompactTextString(m) }
func (*SpaceTimeRequestMsg) ProtoMessage()    {}
func (*SpaceTimeRequestMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c43524b64f4ebcab, []int{5}
}

func (m *SpaceTimeRequestMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpaceTimeRequestMsg.Unmarshal(m, b)
}
func (m *SpaceTimeRequestMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpaceTimeRequestMsg.Marshal(b, m, deterministic)
}
func (m *SpaceTimeRequestMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpaceTimeRequestMsg.Merge(m, src)
}
func (m *SpaceTimeRequestMsg) XXX_Size() int {
	return xxx_messageInfo_SpaceTimeRequestMsg.Size(m)
}
func (m *SpaceTimeRequestMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_SpaceTimeRequestMsg.DiscardUnknown(m)
}

var xxx_messageInfo_SpaceTimeRequestMsg proto.InternalMessageInfo

func (m *SpaceTimeRequestMsg) GetSpaceId() int32 {
	if m != nil {
		return m.SpaceId
	}
	return 0
}

func (m *SpaceTimeRequestMsg) GetCurrentTime() int32 {
	if m != nil {
		return m.CurrentTime
	}
	return 0
}

type SpaceTimeResponseMsg struct {
	SpaceId              int32           `protobuf:"varint,1,opt,name=space_id,json=spaceId,proto3" json:"space_id" query:"space_id"`
	CurrentTime          int32           `protobuf:"varint,2,opt,name=current_time,json=currentTime,proto3" json:"current_time" query:"current_time"`
	ActiveEvents         []*EventMsg     `protobuf:"bytes,3,rep,name=active_events,json=activeEvents,proto3" json:"active_events,omitempty"`
	NbActiveNodes        int32           `protobuf:"varint,4,opt,name=nb_active_nodes,json=nbActiveNodes,proto3" json:"nb_active_nodes" query:"nb_active_nodes"`
	ActiveNodes          []*NodeEventMsg `protobuf:"bytes,5,rep,name=active_nodes,json=activeNodes,proto3" json:"active_nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-" query:"-"`
	XXX_unrecognized     []byte          `json:"-" query:"-"`
	XXX_sizecache        int32           `json:"-" query:"-"`
}

func (m *SpaceTimeResponseMsg) Reset()         { *m = SpaceTimeResponseMsg{} }
func (m *SpaceTimeResponseMsg) String() string { return proto.CompactTextString(m) }
func (*SpaceTimeResponseMsg) ProtoMessage()    {}
func (*SpaceTimeResponseMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c43524b64f4ebcab, []int{6}
}

func (m *SpaceTimeResponseMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpaceTimeResponseMsg.Unmarshal(m, b)
}
func (m *SpaceTimeResponseMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpaceTimeResponseMsg.Marshal(b, m, deterministic)
}
func (m *SpaceTimeResponseMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpaceTimeResponseMsg.Merge(m, src)
}
func (m *SpaceTimeResponseMsg) XXX_Size() int {
	return xxx_messageInfo_SpaceTimeResponseMsg.Size(m)
}
func (m *SpaceTimeResponseMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_SpaceTimeResponseMsg.DiscardUnknown(m)
}

var xxx_messageInfo_SpaceTimeResponseMsg proto.InternalMessageInfo

func (m *SpaceTimeResponseMsg) GetSpaceId() int32 {
	if m != nil {
		return m.SpaceId
	}
	return 0
}

func (m *SpaceTimeResponseMsg) GetCurrentTime() int32 {
	if m != nil {
		return m.CurrentTime
	}
	return 0
}

func (m *SpaceTimeResponseMsg) GetActiveEvents() []*EventMsg {
	if m != nil {
		return m.ActiveEvents
	}
	return nil
}

func (m *SpaceTimeResponseMsg) GetNbActiveNodes() int32 {
	if m != nil {
		return m.NbActiveNodes
	}
	return 0
}

func (m *SpaceTimeResponseMsg) GetActiveNodes() []*NodeEventMsg {
	if m != nil {
		return m.ActiveNodes
	}
	return nil
}

func init() {
	proto.RegisterType((*SpaceMsg)(nil), "m3api.SpaceMsg")
	proto.RegisterType((*SpaceListMsg)(nil), "m3api.SpaceListMsg")
	proto.RegisterType((*EventRequestMsg)(nil), "m3api.EventRequestMsg")
	proto.RegisterType((*NodeEventMsg)(nil), "m3api.NodeEventMsg")
	proto.RegisterType((*EventMsg)(nil), "m3api.EventMsg")
	proto.RegisterType((*SpaceTimeRequestMsg)(nil), "m3api.SpaceTimeRequestMsg")
	proto.RegisterType((*SpaceTimeResponseMsg)(nil), "m3api.SpaceTimeResponseMsg")
}

func init() {
	proto.RegisterFile("m3space.proto", fileDescriptor_c43524b64f4ebcab)
}

var fileDescriptor_c43524b64f4ebcab = []byte{
	// 643 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x54, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0x95, 0x93, 0xe6, 0xc7, 0x37, 0xf6, 0x97, 0x6a, 0x5a, 0xe9, 0x73, 0xbf, 0x4f, 0x40, 0x6a,
	0x04, 0x2d, 0x0b, 0x2a, 0x44, 0x10, 0xac, 0x51, 0xc5, 0x22, 0x12, 0x2d, 0x95, 0xdb, 0xbd, 0xe5,
	0x7a, 0xa6, 0x8d, 0xd5, 0xda, 0x63, 0x66, 0xa6, 0x25, 0x7d, 0x1d, 0x1e, 0x82, 0x77, 0x82, 0x37,
	0x60, 0x87, 0xee, 0x9d, 0x71, 0xea, 0x40, 0x58, 0xb1, 0x62, 0x39, 0xe7, 0x9e, 0x7b, 0x3d, 0xe7,
	0x1c, 0xcf, 0x85, 0xb0, 0x9c, 0xea, 0x3a, 0xcb, 0xc5, 0x41, 0xad, 0xa4, 0x91, 0xac, 0x57, 0x4e,
	0xb3, 0xba, 0xf8, 0x2f, 0x2c, 0xa7, 0xb5, 0x2c, 0x2a, 0x63, 0xd1, 0xf8, 0x73, 0x07, 0x86, 0xa7,
	0xc8, 0x3a, 0xd2, 0x97, 0x6c, 0x07, 0x86, 0xd4, 0x91, 0x16, 0x3c, 0xf2, 0x26, 0xde, 0x7e, 0x2f,
	0x19, 0xd0, 0x79, 0xc6, 0xd9, 0x03, 0x00, 0x5b, 0xaa, 0xb2, 0x52, 0x44, 0x9d, 0x89, 0xb7, 0xef,
	0x27, 0x3e, 0x21, 0xc7, 0x59, 0x29, 0xd8, 0x33, 0xd8, 0xcc, 0x72, 0x53, 0xdc, 0x8a, 0xd4, 0xcc,
	0x95, 0xd0, 0x73, 0x79, 0xcd, 0xa3, 0x2e, 0x4d, 0x18, 0x5b, 0xfc, 0xac, 0x81, 0xd9, 0x73, 0xd8,
	0x2a, 0xb3, 0x45, 0x6a, 0x54, 0x21, 0x75, 0x5a, 0x0b, 0x95, 0xd2, 0x75, 0xa2, 0x0d, 0x62, 0x6f,
	0x96, 0xd9, 0xe2, 0x0c, 0x2b, 0x27, 0x42, 0x9d, 0x20, 0xde, 0xd0, 0x2b, 0xc9, 0x45, 0x9b, 0xde,
	0x5b, 0xd2, 0x8f, 0xb1, 0xb2, 0xa4, 0xef, 0xc0, 0x90, 0xa6, 0x17, 0xa5, 0x88, 0xfa, 0x56, 0x02,
	0x8e, 0x2c, 0x4a, 0xc1, 0xfe, 0x07, 0x1f, 0x4b, 0xb9, 0x94, 0x8a, 0x47, 0x43, 0xaa, 0x21, 0xf7,
	0x10, 0xcf, 0x58, 0x14, 0xb7, 0xa2, 0x32, 0x69, 0xc1, 0x75, 0xe4, 0x4f, 0xba, 0x58, 0x24, 0x60,
	0xc6, 0x75, 0xfc, 0x06, 0x02, 0xf2, 0xe8, 0x7d, 0xa1, 0x0d, 0xfa, 0xb4, 0x07, 0x7d, 0x92, 0xae,
	0x23, 0x6f, 0xd2, 0xdd, 0x1f, 0xbd, 0x1c, 0x1f, 0x90, 0xb7, 0x07, 0x8d, 0x91, 0x89, 0x2b, 0xc7,
	0xdf, 0x3d, 0x18, 0xbf, 0xc3, 0x29, 0x89, 0xf8, 0x78, 0x23, 0x6c, 0x73, 0xdb, 0xe4, 0xce, 0xaa,
	0xc9, 0x8f, 0x60, 0x74, 0xa9, 0xe4, 0x27, 0x33, 0x4f, 0xcd, 0x5d, 0x2d, 0x9c, 0x81, 0x60, 0xa1,
	0xb3, 0xbb, 0x5a, 0xb0, 0x5d, 0x08, 0x1c, 0xa1, 0xa8, 0xb8, 0x58, 0x38, 0xd3, 0x5c, 0xd3, 0x0c,
	0x21, 0xf6, 0x18, 0x42, 0x47, 0x91, 0x17, 0x17, 0x5a, 0x34, 0x4e, 0xb9, 0xbe, 0x0f, 0x84, 0x21,
	0x29, 0x57, 0x22, 0x33, 0x85, 0xac, 0xda, 0x56, 0x05, 0x0d, 0x48, 0x7e, 0xed, 0x41, 0x3f, 0x17,
	0x95, 0x11, 0x2a, 0x1a, 0x4c, 0xbc, 0x96, 0x4a, 0x32, 0x9a, 0x54, 0xda, 0x32, 0xdb, 0x86, 0x5e,
	0x2e, 0xaf, 0xa5, 0x22, 0x53, 0xc3, 0xc4, 0x1e, 0xe2, 0xaf, 0x1e, 0x04, 0x98, 0x0d, 0xe9, 0x47,
	0xe1, 0x31, 0x84, 0xd6, 0x62, 0xcc, 0xb2, 0xf9, 0xc5, 0xba, 0xc9, 0x88, 0x40, 0x64, 0xce, 0x38,
	0x9a, 0xd3, 0xc4, 0xd0, 0x98, 0xe3, 0x52, 0x60, 0x4f, 0xa0, 0x67, 0xa3, 0xef, 0xae, 0xbf, 0x8d,
	0xad, 0xfe, 0x2a, 0x6d, 0x63, 0x8d, 0xb4, 0x00, 0x3c, 0xee, 0x8c, 0xf1, 0x38, 0xfb, 0x17, 0x06,
	0xf8, 0x37, 0xe2, 0x37, 0xad, 0x0f, 0x7d, 0x3c, 0xce, 0x38, 0xdb, 0x83, 0x71, 0x2e, 0xab, 0x4a,
	0xe4, 0x34, 0xad, 0xcc, 0xf4, 0x15, 0x59, 0x11, 0x26, 0xff, 0xdc, 0xc3, 0x47, 0x99, 0xbe, 0x8a,
	0xbf, 0x74, 0x60, 0xb8, 0xd4, 0xd9, 0xd6, 0xe0, 0xad, 0x6a, 0xf8, 0x6b, 0xb2, 0x7f, 0x08, 0xa3,
	0x3a, 0x33, 0xf3, 0x34, 0x37, 0x0b, 0xbc, 0xeb, 0x80, 0x28, 0x3e, 0x42, 0x87, 0x66, 0x31, 0xe3,
	0xeb, 0x23, 0x67, 0x2f, 0xc0, 0x57, 0x52, 0xda, 0x80, 0x23, 0x9f, 0x62, 0xda, 0x72, 0x31, 0xb5,
	0xff, 0x84, 0x64, 0x88, 0x2c, 0x44, 0xe2, 0x53, 0xd8, 0xa2, 0x47, 0x83, 0x1f, 0xfd, 0xcd, 0x1b,
	0xf9, 0x69, 0x11, 0xed, 0x42, 0x90, 0xdf, 0x28, 0x85, 0xfe, 0xd2, 0xed, 0xad, 0x8d, 0x23, 0x87,
	0xe1, 0x9c, 0xf8, 0x9b, 0x07, 0xdb, 0xad, 0xa9, 0xba, 0x96, 0x95, 0x16, 0x7f, 0x3c, 0x96, 0xbd,
	0x82, 0xd0, 0xed, 0x38, 0x8a, 0x53, 0x47, 0xdd, 0x95, 0xc7, 0xbf, 0x54, 0x17, 0x58, 0x16, 0x9d,
	0x35, 0x7b, 0x0a, 0xe3, 0xea, 0x3c, 0x75, 0x8d, 0xb4, 0xc5, 0x5c, 0x72, 0x61, 0x75, 0xfe, 0x96,
	0x50, 0x5a, 0x60, 0xec, 0x35, 0x04, 0x2b, 0xa4, 0x1e, 0x0d, 0x5f, 0x6b, 0xdf, 0x28, 0xbb, 0xef,
	0x3b, 0xef, 0xd3, 0x1e, 0x9f, 0xfe, 0x08, 0x00, 0x00, 0xff, 0xff, 0xbc, 0xae, 0x0f, 0x3a, 0xee,
	0x05, 0x00, 0x00,
}
