name: Go

on:
  push:
    branches: [ prod ]
  pull_request:
    branches: [ prod ]

env:
  GOPROXY: https://fredsimon.artifactoryonline.com/artifactory/api/go/go

jobs:
  backend:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      working-directory: backend
    steps:
      - name: Set up Go 1.13 or above
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -v ./m3db
