name: Go
on:
  push:
    branches:
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Test QSM Client
        run: |
          cd client
          export GOPROXY="https://fredsimon.artifactoryonline.com/artifactory/api/go/go"
          go test ./clpoint/
