name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Set up *nix dependencies
        run: |
          sudo -E sed -i ""  "s#^deb http://[^ ]* #deb https://fredsimon.jfrog.io/artifactory/debian #g;" apt-sources.list
          sudo -E apt-add-repository -y "deb https://fredsimon.jfrog.io/artifactory/debian bionic InRelease"
          sudo apt-get install postgresql
          export PATH=/usr/lib/postgresql/10/bin:$PATH

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get Go dependencies
        run: |
          export GOPROXY="https://fredsimon.artifactoryonline.com/artifactory/api/go/go"
          go mod download
          go get -v -t -d ./...

      - name: Build
        run: go build -v .

      - name: Start and clean PostgreSQL
        run: ./qsm db check && ./qsm db dropAll

      - name: Run All Tests
        run: ./qsm test all
